import type { CivilizationId, WikiId, Civilization } from "@/types"

export const TOP_CIVILIZATIONS = [
  {
    id: "granbell" as CivilizationId,
    rank: 1,
    name: "グランベル",
    nameEn: "Granbell",
    color: "text-amber-400",
    borderColor: "border-amber-400/30 hover:border-amber-400/60",
    bgColor: "from-amber-500/20 via-amber-600/10 to-amber-700/20",
    icon: "Crown",
    leader: "アルゼン・カーリーン大統領",
    leaderWikiId: "アルゼン・カーリーン" as WikiId,
    capital: "オルダシティ",
    gdp: "150京ドル（宇宙全体の約25%）",
    specialization: "量子経済・次元間技術・マルチバース開拓",
    description:
      "宇宙最大の経済圏。GDP150兆ドルで宇宙全体の約25%を占める圧倒的な経済大国。首都オルダシティは宇宙最大の金融センターであり、量子経済システムと次元間技術で他勢力を完全に圧倒している。",
    history:
      "台頭前は宇宙第2位のGDP。アポロン・Dominion大戦を傍観し、戦後の混乱期に他勢力が疲弊する中で急浮上した。初期リーダーはマスター・クインシアスであり、セリアのドミニクス時代を高く評価していた。アルゼン・カーリーン大統領の下で経済帝国を完成させ、現在に至る。エヴァトロンに対し高次元エネルギー兵器、量子制御ミサイル、重力崩壊弾頭などの武器供与を行った。",
    currentStatus:
      "第一回宇宙連合会合の開催地。カーリーン大統領が「争いを超え、共存と繁栄の道を見つけることが次世代への責任」と演説するなど、表向きは協調路線。しかし、その経済的支配力は他勢力に緊張を与えている。",
    relationships: [
      "エレシオン — 経済援助と医療技術供与のパートナー",
      "ティエリア — ヘゲモニー・パラドックスの危険性が指摘される対立関係",
      "ファルージャ — 文化外交面での協力",
      "ディオクレニス — 科学技術分野での提携",
      "エヴァトロン — 武器供与を通じた影響力拡大",
    ],
    specializationEn: "Quantum Economics \u00b7 Interdimensional Technology \u00b7 Multiverse Exploration",
    descriptionEn: "The largest economic sphere in the cosmos. With a GDP of 150 quadrillion dollars, it accounts for approximately 25% of the entire cosmos. As an overwhelming economic superpower, its capital Old City is the cosmos's largest financial center, completely dominating other powers through quantum economic systems and interdimensional technology.",
    historyEn: "Before its rise, it held the second-highest GDP in the cosmos. After observing the Apollo-Dominion War from the sidelines, it rapidly ascended during the post-war chaos while other powers were exhausted. The initial leader was Master Quinsias, who held Celia's Dominix era in high regard. Under President Arzen Carleen, it completed its economic empire and continues to the present. It provided Evatron with higher-dimensional energy weapons, quantum-guided missiles, and gravitational collapse warheads.",
    currentStatusEn: "Host of the First Cosmic Assembly. While ostensibly pursuing a cooperative path, with President Carleen declaring that 'transcending conflict to find the path of coexistence and prosperity is our responsibility to the next generation,' its overwhelming economic dominance creates tension with other powers.",
    relationshipsEn: ["Elyseon \u2014 Economic aid and medical technology supply partnership", "Tyeria \u2014 Adversarial relationship with Hegemony Paradox concerns", "Fallujah \u2014 Cultural diplomacy cooperation", "Dioclenis \u2014 Scientific technology collaboration", "Evatron \u2014 Influence expansion through weapons supply"],
    planets: ["グランベル・プライム", "ノヴァ・エコー", "クインシアス", "ヴェルディ・ステーション"],
    wikiId: "グランベル" as WikiId,
    href: "/civilizations/granbell",
  },
  {
    id: "elyseon" as CivilizationId,
    rank: 2,
    name: "エレシオン",
    nameEn: "Elyseon",
    color: "text-emerald-400",
    borderColor: "border-emerald-400/30 hover:border-emerald-400/60",
    bgColor: "from-emerald-500/20 via-emerald-600/10 to-emerald-700/20",
    icon: "Heart",
    leader: "女王リアナ・ソリス",
    leaderWikiId: "女王リアナ・ソリス" as WikiId,
    specialization: "医療技術・環境再生技術・平和外交",
    description:
      "医療技術と環境再生技術で宇宙をリードする平和主義文明圏。支配ではなく「生命の維持と再生」を根幹理念とし、他文明圏からの尊敬を集めている。",
    history:
      "長年にわたり医療・環境分野で技術革新を続け、多くの文明圏に技術を提供してきた。リアナ・ソリス女王の治世の下、平和外交を宇宙規模で展開し、対立の緩和に寄与している。",
    currentStatus:
      "ティエリアの軍拡路線に強く反対。ディオクレニスの宇宙探査提案を支持。グランベルの宇宙連合会合で平和的解決を訴え、技術共有の推進を掲げる。",
    relationships: [
      "グランベル — 経済援助と技術供与の関係",
      "ティエリア — 軍拡反対で対立",
      "ディオクレニス — 宇宙探査提案に協力的",
      "ファルージャ — 平和外交で連携",
    ],
    specializationEn: "Medical Technology \u00b7 Environmental Regeneration Technology \u00b7 Peace Diplomacy",
    descriptionEn: "A pacifist civilization leading the cosmos in medical technology and environmental regeneration technology. Rather than domination, it positions 'the preservation and regeneration of life' as its foundational principle, earning respect from other civilizations.",
    historyEn: "Having continuously pursued technological innovation in medical and environmental fields for many years, it has provided technology to numerous civilizations. Under Queen Liana Solis's reign, it has deployed peace diplomacy on a cosmic scale, contributing to the alleviation of conflicts.",
    currentStatusEn: "Strongly opposes Tyeria's military expansion path. Supports Dioclenis's cosmic exploration proposal. At the Cosmic Assembly in Granbell, it advocated for peaceful resolution and promoted technology sharing.",
    relationshipsEn: ["Granbell \u2014 Economic aid and technology supply relationship", "Tyeria \u2014 Opposition over military expansion", "Dioclenis \u2014 Supportive of exploration proposal", "Fallujah \u2014 Peace diplomacy cooperation"],
    planets: ["エレシオン・プライム", "ソラリス", "ヴィータ", "リーファ"],
    wikiId: "エレシオン" as WikiId,
    href: "/civilizations/elyseon",
  },
  {
    id: "tyeria" as CivilizationId,
    rank: 3,
    name: "ティエリア",
    nameEn: "Tyeria",
    color: "text-rose-400",
    borderColor: "border-rose-400/30 hover:border-rose-400/60",
    bgColor: "from-rose-500/20 via-rose-600/10 to-rose-700/20",
    icon: "Shield",
    leader: "総帥グレイモンド・ハウザー",
    leaderWikiId: "グレイモンド・ハウザー" as WikiId,
    specialization: "軍事力・防衛ネットワーク・軍事技術輸出",
    description:
      "宇宙最強の軍事力を誇る文明圏。軍事技術の輸出を経済基盤とし、その防衛ネットワークは宇宙随一と言われる。グレイモンド・ハウザー総帥の下、「軍事力なくして平和は守れない」という信条に基づき強大な軍備を維持している。",
    history:
      "古くから軍事技術の研究に注力し、他文明圏に対する軍事技術輸出で経済基盤を確立。グランベルの経済的支配が進む中、軍事力で均衡を保つ政策をとってきた。",
    currentStatus:
      "グランベルの経済的支配に対し軍事力で均衡を図る。エレシオンのリアナ女王とは軍拡を巡って対立。ヘゲモニー・パラドックスの危険性が指摘されている。",
    relationships: [
      "グランベル — 経済vs軍事の構造的対立",
      "エレシオン — 軍拡方針で対立",
      "ファルージャ — 調停の対象",
      "ディオクレニス — ヘゲモニー・パラドックスの提起者",
    ],
    specializationEn: "Military Power \u00b7 Defense Network \u00b7 Military Technology Exports",
    descriptionEn: "A civilization boasting the strongest military power in the cosmos. Using military technology exports as its economic foundation, its defense network is said to be unparalleled in the cosmos. Under Supreme Commander Greymond Hauser, it maintains formidable military capabilities based on the conviction that 'peace cannot be protected without military strength.'",
    historyEn: "Having long focused on military technology research, it established its economic foundation through military technology exports to other civilizations. As Granbell's economic dominance grew, it pursued policies to maintain balance through military power.",
    currentStatusEn: "Using military power to balance against Granbell's economic dominance. In conflict with Elyseon's Queen Liana over military expansion. The danger of a Hegemony Paradox has been pointed out.",
    relationshipsEn: ["Granbell \u2014 Structural opposition of economy versus military", "Elyseon \u2014 Opposition over military expansion policy", "Fallujah \u2014 Subject of mediation", "Dioclenis \u2014 Raiser of the Hegemony Paradox"],
    planets: ["ティエリア・フォートレス", "シールド・バース", "アーミーナ", "ヴァンガード"],
    wikiId: "ティエリア" as WikiId,
    href: "/civilizations/tyeria",
  },
  {
    id: "fallujah" as CivilizationId,
    rank: 4,
    name: "ファルージャ",
    nameEn: "Fallujah",
    color: "text-violet-400",
    borderColor: "border-violet-400/30 hover:border-violet-400/60",
    bgColor: "from-violet-500/20 via-violet-600/10 to-violet-700/20",
    icon: "Scale",
    leader: "評議会代表マドリス・カーネル",
    leaderWikiId: "マドリス・カーネル" as WikiId,
    specialization: "文化的影響力・外交・勢力間調停",
    description:
      "文化的影響力と外交力で宇宙に君臨する文明圏。対立する勢力間の調停役として重要な地位を占め、「文化の力が宇宙全体を結びつける鍵」という理念を掲げている。",
    history:
      "古くから文化・芸術分野で独自の発展を遂げ、他文明圏に文化的影響を与え続けてきた。マドリス・カーネル代表の下、外交による問題解決を推進。",
    currentStatus:
      "グランベルの経済的支配に対する懸念を表明。ティエリアとエレシオンの対立の調停を試みる。宇宙連合会合で文化的交流の促進を提案。",
    relationships: [
      "グランベル — 経済的支配への懸念",
      "ティエリア — 調停の対象",
      "エレシオン — 平和外交で連携",
      "ディオクレニス — 文化交流で協力",
    ],
    specializationEn: "Cultural Influence \u00b7 Diplomacy \u00b7 Inter-Power Mediation",
    descriptionEn: "A civilization reigning over the cosmos through cultural influence and diplomacy. It occupies an important position as a mediator between opposing powers, championing the philosophy that 'the power of culture is the key that binds the entire cosmos together.'",
    historyEn: "Having achieved unique development in cultural and artistic fields since ancient times, it has continuously exerted cultural influence on other civilizations. Under Representative Madris Cernel, it has promoted conflict resolution through diplomacy.",
    currentStatusEn: "Has expressed concerns about Granbell's economic dominance. Attempting to mediate the conflict between Tyeria and Elyseon. At the Cosmic Assembly, it proposed promoting cultural exchange.",
    relationshipsEn: ["Granbell \u2014 Concerns over economic dominance", "Tyeria \u2014 Subject of mediation", "Elyseon \u2014 Peace diplomacy cooperation", "Dioclenis \u2014 Cultural exchange cooperation"],
    planets: ["ファルージャ・ハブ", "アーティザ", "ビブロ", "メロディ"],
    wikiId: "ファルージャ" as WikiId,
    href: "/civilizations/fallujah",
  },
  {
    id: "dioclenis" as CivilizationId,
    rank: 5,
    name: "ディオクレニス",
    nameEn: "Dioclenis",
    color: "text-cyan-400",
    borderColor: "border-cyan-400/30 hover:border-cyan-400/60",
    bgColor: "from-cyan-500/20 via-cyan-600/10 to-cyan-700/20",
    icon: "Telescope",
    leader: "科学宰相ネイサン・コリンド",
    leaderWikiId: "ネイサン・コリンド" as WikiId,
    specialization: "宇宙探査・科学技術研究",
    description:
      "宇宙探査と科学技術研究の最前線に立つ文明圏。科学宰相ネイサン・コリンドの下、「ヘゲモニー・パラドックス」を提起し、宇宙共同探査プロジェクトを提案するなど、先見性のある政策を展開。",
    history:
      "科学技術の研究開発に特化し、宇宙探査の分野で多大な成果を挙げてきた。ネイサン・コリンドの下、4つの具体的提案（平和協定、UECO設立、技術共有、文化交流）を行った。",
    currentStatus:
      "宇宙連合会合で宇宙共同探査プロジェクトを提案。グランベルとティエリアの対立に「ヘゲモニー・パラドックス」の概念を適用し、警告を発している。",
    relationships: [
      "グランベル — ヘゲモニー・パラドックスの対象",
      "ティエリア — ヘゲモニー・パラドックスの対象",
      "エレシオン — 探査提案に支持",
      "ファルージャ — 文化交流で協力",
    ],
    specializationEn: "Cosmic Exploration \u00b7 Scientific Technology Research",
    descriptionEn: "A civilization at the forefront of cosmic exploration and scientific technology research. Under Science Chancellor Nathan Corind, it has demonstrated foresight by proposing the 'Hegemony Paradox' and advancing a joint cosmic exploration project.",
    historyEn: "Having specialized in scientific technology research and development, it has achieved remarkable results in cosmic exploration. Under Nathan Corind, it made four concrete proposals: a peace agreement, UECO establishment, technology sharing, and cultural exchange.",
    currentStatusEn: "Proposed a joint cosmic exploration project at the Cosmic Assembly. Applied the Hegemony Paradox concept to the Granbell-Tyeria conflict and issued warnings.",
    relationshipsEn: ["Granbell \u2014 Subject of the Hegemony Paradox", "Tyeria \u2014 Subject of the Hegemony Paradox", "Elyseon \u2014 Supportive of exploration proposal", "Fallujah \u2014 Cultural exchange cooperation"],
    planets: ["コリンド・ステーション", "ネオ・フロンティア", "オデッセイ", "スペクトラ"],
    wikiId: "ディオクレニス" as WikiId,
    href: "/civilizations/dioclenis",
  },
] as const satisfies readonly Civilization[]
