import type { CivilizationId, WikiId, Civilization } from "@/types"

export const HISTORICAL_CIVILIZATIONS = [
  {
    id: "dominion" as CivilizationId,
    rank: 0,
    name: "Dominion / Selinopolis",
    nameEn: "Dominion / Selinopolis",
    color: "text-edu-accent",
    borderColor: "border-edu-accent/30 hover:border-edu-accent/60",
    bgColor: "from-amber-500/20 via-edu-accent/10 to-amber-600/20",
    icon: "Crown",
    leader: "セリア・ドミニクス",
    leaderWikiId: "セリア・ドミニクス" as WikiId,
    capital: "Selinopolis（旧Gigapolis）",
    gdp: "81兆ドル（最盛期）→ 23兆ドル（大戦後）",
    specialization: "次元エネルギー技術（Phovos）・女性主導社会",
    description:
      "セリア・ドミニクスがGigapolisを掌握しSelinopolisに改名して建国。次元エネルギー技術のPhovosを中核とし、女性主導社会で繁栄した。最盛期GDP81兆ドル。アポロン大戦後はエヴァトロンに吸収される。",
    history:
      "E335〜E370年のセリア黄金期。フェルミ音楽の頂点、nトークン経済の確立、AURALISの最盛期を導いた。アポロン大戦にエヴァトロンと共に参戦したが、戦後GDP23兆に激減。その後、ヴァイロン・デアクス率いるエヴァトロンによって買収・吸収された。",
    currentStatus: "現在はエヴァトロンに吸収され、E16系を支配下に置いている。",
    relationships: [
      "エヴァトロン — 同盟→吸収",
      "アポロン文明圏 — 全面戦争",
      "グランベル — マスター・クインシアスがセリアを高評価",
    ],
    specializationEn: "Dimensional Energy Technology (Phovos) \u00b7 Female-Led Society",
    descriptionEn: "Founded when Celia Dominix seized control of Gigapolis and renamed it Selinopolis. Centered on the dimensional energy technology Phovos, it prospered as a female-led society. Peak GDP of 81 trillion dollars. After the Apollon War, it was absorbed by Evatron.",
    historyEn: "The Celia Golden Age from E335 to E370. Led to the peak of Fermi music, establishment of the n-token economy, and the zenith of AURALIS. Fought alongside Evatron in the Apollon War, but post-war GDP plummeted to 23 trillion. Subsequently, it was acquired and absorbed by Evatron under Viron Daxe's leadership.",
    currentStatusEn: "Currently absorbed by Evatron, which controls the E16 system under its authority.",
    relationshipsEn: ["Evatron \u2014 Alliance \u2192 Absorption", "Apollon Civilization \u2014 Total war", "Granbell \u2014 Master Quinsias held Celia in high regard"],
    planets: ["Symphony of Stars", "Eros-7", "E16小惑星帯"],
    wikiId: "セリア・ドミニクス" as WikiId,
    href: "",
    isHistorical: true,
  },
  {
    id: "apollon" as CivilizationId,
    rank: 0,
    name: "アポロン文明圏",
    nameEn: "Apollon Civilization",
    color: "text-red-400",
    borderColor: "border-red-400/30 hover:border-red-400/60",
    bgColor: "from-red-500/20 via-red-600/10 to-red-700/20",
    icon: "Swords",
    leader: "ロナン・アーサ",
    leaderWikiId: "ロナン・アーサ" as WikiId,
    capital: "アポロン・セントラリス",
    gdp: "125兆ドル（最盛期）→ 32億ドル（大戦後）",
    specialization: "アポロンの騎士団・ケンタウロスレーザー",
    description:
      "ロナン・アーサ率いる英雄的文明圏。最盛期GDP125兆ドル。アポロンの騎士団とケンタウロスレーザーを擁し、Dominionとの全面戦争を戦ったが、セリアのヴェノム艦隊により壊滅。",
    history:
      "ロナン・アーサがセリアに同盟を提案したが拒絶されたことが戦争の端緒。ケンタウロスレーザーとG4ファントムパルスが交差する激戦の末、セリアのヴェノム艦隊がアポロン・セントラリスを攻略。GDP32億に激減し、文明圏としての機能を失った。",
    currentStatus: "壊滅状態。GDP32億ドルに激減。",
    relationships: ["Dominion — 同盟拒絶→全面戦争", "エヴァトロン — 戦後の混乱に関連"],
    specializationEn: "Order of Apollon \u00b7 Centaurus Laser",
    descriptionEn: "A heroic civilization led by Ronan Arthur. Peak GDP of 125 trillion dollars. Possessing the Order of Apollon and the Centaurus Laser, it fought a total war against Dominion but was annihilated by Celia's Venom Fleet.",
    historyEn: "The war began when Ronan Arthur's alliance proposal to Celia was rejected. After fierce battles where the Centaurus Laser and G4 Phantom Pulse clashed, Celia's Venom Fleet conquered Apollon Centralis. GDP plummeted to 3.2 billion, and the civilization lost all functionality.",
    currentStatusEn: "Annihilated. GDP plummeted to 3.2 billion dollars.",
    relationshipsEn: ["Dominion \u2014 Alliance rejected \u2192 Total war", "Evatron \u2014 Related to post-war chaos"],
    planets: ["アポロン・セントラリス（崩壊）", "アレス", "ヘファイストス", "アテナ"],
    wikiId: "アポロン・Dominion大戦" as WikiId,
    href: "",
    isHistorical: true,
  },
  {
    id: "evatron" as CivilizationId,
    rank: 14,
    name: "エヴァトロン",
    nameEn: "Evatron",
    color: "text-gray-400",
    borderColor: "border-gray-400/30 hover:border-gray-400/60",
    bgColor: "from-gray-500/20 via-gray-600/10 to-gray-700/20",
    icon: "Skull",
    leader: "グリム・ダルゴス（初代）→ ヴァイロン・デアクス",
    leaderWikiId: "グリム・ダルゴス" as WikiId,
    capital: "Evapolis",
    gdp: "33兆ドル（同盟時）→ 14位（現在）",
    specialization: "男尊女卑文化・E16系支配",
    description:
      "男尊女卑文化を基盤とする文明圏。グリム・ダルゴスが初代リーダー。Dominionと同盟しアポロン大戦に参戦。戦後、疲弊したDominionを買収・吸収。ヴァイロン・デアクスが統治者に任命され、E16系を支配下に置いた。",
    history:
      "セリアとの同盟を承認。アポロン大戦ではDominion側として参戦。戦後、ヴァイロン・デアクスが戦後の疲弊したDominionを買収・吸収。エヴァトロンの文化・価値観をDominion全土に浸透させた。現在もE16系に影響を与え続けている。",
    currentStatus: "現在14位。セリアンズの抵抗に直面。",
    relationships: [
      "Dominion — 同盟→吸収",
      "アポロン文明圏 — 大戦の敵対",
      "セリアンズ — 抵抗に直面",
    ],
    specializationEn: "Patriarchal Culture \u00b7 E16 System Domination",
    descriptionEn: "A civilization based on patriarchal culture. Grim Dargos was the founding leader. Allied with Dominion and participated in the Apollon War. Post-war, it acquired and absorbed the exhausted Dominion. Viron Daxe was appointed as ruler, placing the E16 system under its control.",
    historyEn: "Approved an alliance with Celia. Fought on the Dominion side in the Apollon War. Post-war, Viron Daxe acquired and absorbed the exhausted Dominion. Evatron's culture and values permeated throughout Dominion's territory. It continues to influence the E16 system to this day.",
    currentStatusEn: "Currently ranked 14th. Facing resistance from the Celians.",
    relationshipsEn: ["Dominion \u2014 Alliance \u2192 Absorption", "Apollon Civilization \u2014 War adversaries", "Celians \u2014 Facing resistance"],
    planets: ["エヴァ・プライム", "Evapolis（Gigapolis）", "ゴルゴン", "タルタロス"],
    wikiId: "エヴァトロン" as WikiId,
    href: "",
    isHistorical: true,
  },
] as const satisfies readonly Civilization[]
