import type { CivilizationLeader } from "@/types"

export const CIVILIZATION_LEADERS = [
  {
    name: "アルゼン・カーリーン",
    nameEn: "Arzen Carleen",
    title: "グランベル大統領",
    titleEn: "President of Granbell",
    civilization: "グランベル",
    civilizationEn: "Granbell",
    civilizationColor: "text-amber-400",
    wealth: "150兆ドル（国家GDP）",
    wealthEn: "150 Quadrillion Dollars (National GDP)",
    source: "宇宙最大経済圏の指導",
    sourceEn: "Leader of the cosmos's largest economic sphere",
    era: "現在",
    eraEn: "Present",
    wikiId: "アルゼン・カーリーン",
  },
  {
    name: "女王リアナ・ソリス",
    nameEn: "Queen Liana Solis",
    title: "エレシオン女王",
    titleEn: "Queen of Elyseon",
    civilization: "エレシオン",
    civilizationEn: "Elyseon",
    civilizationColor: "text-emerald-400",
    wealth: "医療技術・環境再生（非公開）",
    wealthEn: "Medical Technology & Environmental Regeneration (Undisclosed)",
    source: "宇宙第2位の医療大国",
    sourceEn: "The cosmos's second-largest medical powerhouse",
    era: "現在",
    eraEn: "Present",
    wikiId: "女王リアナ・ソリス",
  },
  {
    name: "総帥グレイモンド・ハウザー",
    nameEn: "Supreme Commander Greymond Hauser",
    title: "ティエリア総帥",
    titleEn: "Supreme Commander of Tyeria",
    civilization: "ティエリア",
    civilizationEn: "Tyeria",
    civilizationColor: "text-rose-400",
    wealth: "軍事技術輸出（非公開）",
    wealthEn: "Military Technology Exports (Undisclosed)",
    source: "宇宙最強の軍事力",
    sourceEn: "The cosmos's strongest military power",
    era: "現在",
    eraEn: "Present",
    wikiId: "グレイモンド・ハウザー",
  },
  {
    name: "マドリス・カーネル",
    nameEn: "Madris Cernel",
    title: "ファルージャ評議会代表",
    titleEn: "Representative of the Fallujah Council",
    civilization: "ファルージャ",
    civilizationEn: "Fallujah",
    civilizationColor: "text-violet-400",
    wealth: "文化外交収入（非公開）",
    wealthEn: "Cultural Diplomacy Revenue (Undisclosed)",
    source: "宇宙第4位の文化的影響力",
    sourceEn: "The cosmos's fourth-largest cultural influence",
    era: "現在",
    eraEn: "Present",
    wikiId: "マドリス・カーネル",
  },
  {
    name: "ネイサン・コリンド",
    nameEn: "Nathan Corind",
    title: "ディオクレニス科学宰相",
    titleEn: "Science Chancellor of Dioclenis",
    civilization: "ディオクレニス",
    civilizationEn: "Dioclenis",
    civilizationColor: "text-cyan-400",
    wealth: "科学技術研究費（非公開）",
    wealthEn: "Scientific Research Expenditure (Undisclosed)",
    source: "宇宙探査の最前線",
    sourceEn: "At the forefront of cosmic exploration",
    era: "現在",
    eraEn: "Present",
    wikiId: "ネイサン・コリンド",
  },
  {
    name: "大司教",
    nameEn: "The Archbishop",
    title: "エレシュ大司教",
    titleEn: "Archbishop of Eresh",
    civilization: "エレシュ",
    civilizationEn: "Eresh",
    civilizationColor: "text-purple-400",
    wealth: "宗教的影響力（非公開）",
    wealthEn: "Religious Influence (Undisclosed)",
    source: "宇宙最大の信仰共同体",
    sourceEn: "The cosmos's largest faith community",
    era: "現在",
    eraEn: "Present",
    wikiId: "大司教",
  },
  {
    name: "商工会議長",
    nameEn: "Trade Council Chairman",
    title: "プロキオ商工会議長",
    titleEn: "Trade Council Chairman of Prokio",
    civilization: "プロキオ",
    civilizationEn: "Prokio",
    civilizationColor: "text-orange-400",
    wealth: "全宇宙貿易取引（非公開）",
    wealthEn: "All-Cosmos Trade Transactions (Undisclosed)",
    source: "宇宙全貿易ルートの掌握",
    sourceEn: "Controller of all trade routes in the cosmos",
    era: "現在",
    eraEn: "Present",
    wikiId: "商工会議長",
  },
  {
    name: "通信長官",
    nameEn: "Communications Commissioner",
    title: "ロースター通信長官",
    titleEn: "Communications Commissioner of Roastar",
    civilization: "ロースター",
    civilizationEn: "Roastar",
    civilizationColor: "text-pink-400",
    wealth: "通信インフラ収入（非公開）",
    wealthEn: "Communication Infrastructure Revenue (Undisclosed)",
    source: "全宇宙通信インフラの管理",
    sourceEn: "Manager of all-cosmos communication infrastructure",
    era: "現在",
    eraEn: "Present",
    wikiId: "通信長官",
  },
] as const satisfies readonly CivilizationLeader[]
