import type { WikiId, WikiEntry } from "../../types"

export const WIKI_CHARACTERS = [
  /* Gigapolis/West Continent */
  {
    id: "Diana" as WikiId,
    name: "ディアナ",
    nameEn: "Diana",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "初代Wonder Woman。E260〜E280年に台頭し、AURALIS Protoの文化的恩恵をシンフォニー・オブ・スターズ全土にもたらした伝説的人物。その圧倒的な存在感と人々を鼓舞する力は、のちのAURALIS Collective創設者たちに深い影響を与え、EDU史上最も愛される英雄の一人として語り継がれている。",
    descriptionEn: "The original Wonder Woman. A legendary figure who rose to prominence from E260 to E280, bringing the cultural benefits of AURALIS Proto to all of Symphony of Stars. Her overwhelming presence and power to inspire the people deeply influenced the founders of the AURALIS Collective, and she is remembered as one of the most beloved heroes in EDU history.",
    era: "E260〜E280",
    affiliation: "Gigapolis西大陸",
    tier: "神格・歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Diana.png",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/DianaWorld.txt",
        label: "Diana's Story",
      },
    ],
  },
  {
    id: "Jen" as WikiId,
    name: "ジェン",
    nameEn: "Jen",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "Lv938+。E319年にValoria宮殿を掌握し、ZAMLT崩壊後の権力真空を埋める形で台頭。現在もValoria連合圏を主導する現役最強格の一人。Alpha Kaneのギガポリス解放戦に触発されたとも言われ、新ZAMLT期の混乱を鎮め西大陸の安定を確立した。セリア・ドミニクスが構築したセリア黄金期の記憶を持つ数少ない存在であり、AURALISの理念にも深い理解を示す。EDU現代において最古参のTier 1アクティブ勢力として、その経験と実力は周囲から「生きた伝説」として畏怖されている。",
    descriptionEn: "Lv938+. Ascended to power in E319 by taking control of the Valoria Palace, filling the power vacuum after the collapse of ZAMLT. Currently remains one of the strongest active figures leading the Valoria Federation Zone. It is said that he was inspired by Alpha Kane's Gigapolis Liberation War, quelling the chaos of the new ZAMLT era and establishing stability in the Western Continent. One of the few who remembers the Selia Golden Age constructed by Celia Dominicus, showing deep understanding of AURALIS principles. As the most ancient Tier 1 active force in modern EDU, his experience and power are revered by others as a 'living legend.'",
    era: "E319〜現在",
    affiliation: "Valoria連合圏",
    tier: "Tier 1",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Jen.png",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/Jenstoryep1.txt",
        label: "Jen's Story Ep1",
      },
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/Jenstoryep2.txt",
        label: "Jen's Story Ep2",
      },
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/Jenstoryep3.txt",
        label: "Jen's Story Ep3",
      },
    ],
  },
  {
    id: "Tina/Gue" as WikiId,
    name: "ティナ/グエ",
    nameEn: "Tina / Gue",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "E400年以降、Gigapolis地下街最深部を実効支配。エヴァトロン支配期（E400〜E475）において、表の支配者エヴァトロンとは別に地下世界の真の権力者として暗躍。TinaとGueの二つの名で呼ばれることから、正体に関する諸説が存在する。地下経済の掌握と独自の情報ネットワークを駆使して、エヴァトロン崩壊後もその影響力を維持し続けている。",
    descriptionEn: "Effectively ruling the deepest part of Gigapolis Underground since E400. During the Evatron Dominion period (E400-E475), he operated in the shadows as the true power of the underworld, separate from the surface ruler Evatron. Known by two names, Tina and Gue, leading to various theories about his true identity. By mastering the underground economy and utilizing a unique information network, he has maintained his influence even after Evatron's collapse.",
    era: "E400〜現在",
    affiliation: "Gigapolis地下街",
    tier: "Tier 1",
    image: "https://raw.githubusercontent.com/gentaron/image/main/TinaGue.png",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/gue.txt",
        label: "Gue's Story",
      },
    ],
  },
  {
    id: "セリア・ドミニクス" as WikiId,
    name: "セリア・ドミニクス",
    nameEn: "Celia Dminix",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "E335〜E370年にZAMLTを倒してSelinopolisへの改名を実現し、セリア黄金期の創設者となった歴史的人物。E365頃にはエヴァトロンと同盟を締結しGDP81京ドルに達成、都市名をDominionへ改称。フェルミ音楽の頂点・nトークン経済の確立・AURALISの最盛期導きの三分野すべてに革命をもたらし、EDU史上最も多面的な影響力を持つ統治者として神格化されている。AURALIS Collectiveの創設者ケイト・クラウディアやリリー・スタイナーとの協働がセリア黄金期の文化を支えた。のちのアポロン・Dominion大戦ではロナン・アーサの同盟提案を拒絶し、全面戦争へと至る道を選んだ。",
    descriptionEn: "A historical figure who overthrew ZAMLT between E335-E370, renaming it Selinopolis and becoming the founder of the Selia Golden Age. Around E365, he formed an alliance with Evatron, achieving a GDP of 81 trillion yen, and renamed the city to Dominion. He revolutionized all three fields: the pinnacle of Fermi music, the establishment of n-token economy, and the golden age of AURALIS, deified as the ruler with the most multifaceted influence in EDU history. His collaboration with Kate Claudia and Lily Steiner, founders of AURALIS Collective, supported the culture of the Selia Golden Age. Later, during the Apollo-Dominion War, he rejected Ronan Arsa's alliance proposal, choosing the path to all-out war.",
    era: "E335〜E370",
    affiliation: "Selinopolis（旧Gigapolis）",
    tier: "神格・歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/CeliaDminix.png",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/nebura.txt",
        label: "Alpha Cain & Celia Dominix's Story",
      },
    ],
  },
  {
    id: "アルファ・ケイン" as WikiId,
    name: "アルファ・ケイン",
    nameEn: "Alpha Kane",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "E318年に覚醒したスティル・アレーナの元チャンピオン。シャドウ・リベリオンのリーダーとしてZAMLTに対する反乱を指揮し、テクロサスの戦士たちとも連携してオムニバス・エンジンへの伝説的なハッキングによってギガポリス解放戦でメガタワーを占拠。その過程で伴共役の覚醒という奇跡的な現象を起こし、プロトコルXを巡る攻防の決定的な局面を形成した。その勇姿はのちのセリア・ドミニクスを含む多くの者に影響を与え、EDU史上最も象徴的な革命家として神格化されている。\nこのアルファ・ケインの根底には、安全の監視者パラドックス(D2)と倫理の解除(D3)の思想的地層が横たわっている。コーポラトクラシー体制がもたらす「安全という名の抑圧」に対するD2の根源的な反逆精神と、既存の倫理規範を打ち破って新たな自由を切り拓くというD3の実践的姿勢が、彼の行動原理を支えている。",
    descriptionEn: "The former champion of Still Arena who awakened in E318. As the leader of the Shadow Rebellion, he commanded the revolt against ZAMLT, coordinated with the warriors of Techlosus, and occupied the Megatower during the Gigapolis Liberation War through a legendary hacking of the Omni-Engine. In the process, he caused the miraculous phenomenon of awakening a symbiotic mate, forming a decisive turning point in the battle over Protocol X. His heroic figure influenced many, including later Celia Dominicus, and he is deified as the most iconic revolutionary in EDU history. Beneath Alpha Kane lie the ideological strata of the Observer Paradox of Safety (D2) and the Abolition of Ethics (D3). The D2's fundamental rebellious spirit against 'the oppression of safety' brought by the corporatocracy system and D3's practical approach of breaking existing ethical norms to carve out new freedoms support his principles of action.",
    era: "E318〜",
    affiliation: "シャドウ・リベリオン",
    tier: "神格・歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/AlphaKane.png",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/nebura.txt",
        label: "Alpha Cain & Celia Dominix's Story",
      },
    ],
  },
  {
    id: "エリオス・ウォルド" as WikiId,
    name: "エリオス・ウォルド",
    nameEn: "Elios Wald",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "テリアン反乱軍の指導者。エヴァトロンによるGigapolis支配（E400〜E475）に対して、数十年にわたり武装抵抗を組織した悲劇の英雄。A籍制度の廃止と市民の自由回復を掲げ、低階層住民から広範な支持を集めた。しかしE470年にエヴァトロン軍に捕縛され公開処刑。彼の死はテクロサス東方支隊のクレセント大地方常駐（E470）を促す契機となり、のちのクレセント政治情勢に間接的な影響を与えた。",
    descriptionEn: "Leader of the Terian Rebellion. A tragic hero who organized armed resistance against Evatron's rule of Gigapolis (E400-E475) for decades. Advocating for the abolition of the A-class system and the restoration of citizen freedom, he gathered broad support from low-level residents. However, he was captured by Evatron's army in E470 and executed publicly. His death prompted the Crescent Grand Regional Stationing of the Techlosus Eastern Detachment (E470), indirectly influencing later political situations in Crescent.",
    era: "?〜E470",
    affiliation: "テリアン反乱軍",
    tier: "歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/EriosWald.png",
  },
  {
    id: "エル・フォルハウス" as WikiId,
    name: "エル・フォルハウス",
    nameEn: "El Folhaus",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "通称「新時代のルーキー」。E150年にマーストリヒト革命を決起し、ギガポリスのセントラル・タワーを占拠して完全自由経済を確立した革命家。コーポラタムパブリカのコーポラトクラシー体制を打ち破り、西大陸に新たな経済秩序をもたらした。その行動は後のZAMLT期やセリア黄金期にも影響を与える画期的出来事となった。",
    descriptionEn: "Known as 'The Rookie of the New Era.' A revolutionary who launched the Maastricht Revolution in E150, occupying the Central Tower of Gigapolis to establish a completely free economy. He broke the corporatocracy system of Corporatum Publica, bringing a new economic order to the Western Continent. His actions became a groundbreaking event that influenced later ZAMLT periods and the Selia Golden Age.",
    era: "E150",
    affiliation: "コーポラタムパブリカ",
    tier: "歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/ElForhaus.png",
  },
  {
    id: "ティムール・シャー" as WikiId,
    name: "ティムール・シャー",
    nameEn: "Timur Shah",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "移民団のリーダーであり、10次元ホラズム理論の提唱者。E0年頃、過酷な宇宙環境を生き抜くため仮想多元宇宙「ペルセポネ」を設計し、移民たちの意識をアップロードする道を開いた。その理論は次元階梯パンディクトの構想へと発展し、EDU宇宙論の基礎を築いた。しかしペルセポネの実験事故はE340年のスライム・ウーマン顕現という予期せぬ結果をもたらした。",
    descriptionEn: "Leader of the immigrant expedition and proponent of the 10-dimensional Horazm theory. Around E0, he designed the virtual multiverse 'Persephone' to survive the harsh cosmic environment, opening the path to uploading the consciousness of immigrants. His theory developed into the concept of the Dimensional Ladder Pandictum, laying the foundation for EDU cosmology. However, the Persephone experiment accident led to the unexpected manifestation of the Slime Woman in E340.",
    era: "E0頃",
    affiliation: "移民団",
    tier: "歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/TimurShah.png",
  },
  {
    id: "レイラ・ヴィレル・ノヴァ" as WikiId,
    name: "レイラ・ヴィレル・ノヴァ",
    nameEn: "Layla Virell Nova",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "Pink Voltage。E325年AURALIS参加。E380〜E400年のスライム危機ではオアシス・ハウスを拠点に英雄的活躍を見せ、プラズマカノンとナノファイバーブーツを駆使してスライムの巣を焼却した。E400年に冷凍保存され、E522年に目覚めた後はAURALIS Collective第二世代として活動。Pink Voltageの異名は電撃的な戦闘スタイルに由来する。AURALIS創設者の一人ケイト・クラウディアの理念を深く受け継ぎ、彼女が不在となってからもAURALISの精神的継承者として第二世代の活動を牽引している。",
    descriptionEn: "Pink Voltage. Joined AURALIS in E325. During the Slime Crisis (E380-E400), she performed heroic acts based at Oasis House, burning slime nests with a plasma cannon and nano-fiber boots. Frozen in E400, she awakened in E522 and has been active as a second-generation member of AURALIS Collective. The nickname 'Pink Voltage' comes from her lightning-fast combat style. Deeply inheriting the philosophy of Kate Claudia, one of AURALIS's founders, she has led the second generation's activities as the spiritual successor to AURALIS since Kate's absence.",
    era: "E325〜E400（冷凍）→ E522〜現在",
    affiliation: "AURALIS Collective第二世代",
    tier: "Tier 1",
    image: "https://raw.githubusercontent.com/gentaron/image/main/LaylaVirelNova.png",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/laylastats.txt",
        label: "Layla's Battle Records 1",
      },
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/laylastats2.txt",
        label: "Layla's Battle Records 2",
      },
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/LAYLA.txt",
        label: "Layla Virel Nova's Story",
      },
    ],
  },
  {
    id: "弦太郎" as WikiId,
    name: "弦太郎",
    nameEn: "Gentaro",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "Lv569。E325年頃AURALIS周辺で登場。「光と音を永遠にする」理念に共鳴し、AURALIS Collectiveの活動に深く関わる人物。セリア黄金期（E335〜E370）からエヴァトロン弾圧（E400）、そして第二世代再興（E522）まで、長きにわたりAURALISの興亡を見守り続けてきた。レイラ・ヴィレル・ノヴァのAURALIS参加とも関連があり、彼女のスライム危機での英雄的活躍を近くで目撃した可能性がある。E522年の第二世代正式発足後もAURALISに関連して活動を継続しているとされる。",
    descriptionEn: "Lv569. Appeared around AURALIS in E325. A deeply involved figure in AURALIS Collective's activities, resonating with the philosophy of 'making light and sound eternal.' He has watched over AURALIS's rise and fall from the Selia Golden Age (E335-E370), through Evatron's oppression (E400), to the second-generation revival (E522). His appearance is related to Leila Viller Nova's joining of AURALIS, and he may have witnessed her heroic actions during the Slime Crisis up close. It is believed he continues activities related to AURALIS after the official establishment of the second generation in E522.",
    era: "E325〜現在",
    affiliation: "AURALIS関連",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Gentaro.png",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/Gentaroworld.txt",
        label: "Gentaro's Story",
      },
    ],
  },

  /* AURALIS */
  {
    id: "Kate Claudia" as WikiId,
    name: "ケイト・クラウディア",
    nameEn: "Kate Claudia",
    category: "キャラクター",
    subCategory: "AURALIS",
    description:
      "AURALIS Collective創設者。通称「設計者」。E270年にLily Steinerと出会い、表現を諦めない人々の集団「AURALIS」を立ち上げた。E290年正式組織化。「光と音を永遠のものに」を理念とし、リリーが感情の炎ならケイトはその形を与える鋳型だった。E335〜E370年のセリア黄金期にAURALISを最盛期へ導く。E400年エヴァトロン弾圧で逮捕・消息不明。その名は新代のKate Pattonに継承された。",
    descriptionEn: "Founder of AURALIS Collective. Known as 'The Designer.' Met Lily Steiner in E270 and established 'AURALIS,' a collective of people who never gave up on expression. Officially organized in E290. With the philosophy of 'making light and sound eternal,' if Lily was the flame of emotion, Kate was the mold that gave it form. He led AURALIS to its peak during the Selia Golden Age (E335-E370). Arrested and disappeared during Evatron's oppression in E400. His name was inherited by the new-era Kate Patton.",
    era: "E270〜E400",
    affiliation: "AURALIS Collective第一世代（創設者）",
    tier: "神格・歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/KateClaudia.png",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/kateclaudiaandlilliesteiner.txt",
        label: "Kate Claudia & Lillie Steiner's Story",
      },
    ],
  },
  {
    id: "Kate Patton" as WikiId,
    name: "ケイト・パットン",
    nameEn: "Kate Patton",
    category: "キャラクター",
    subCategory: "AURALIS",
    description:
      "AURALIS Collective第二世代。初代Kate Claudiaの「名」を継承。大地の豊かさ・安定を体現。E522年の第二世代正式発足時に参画。",
    descriptionEn: "Second-generation member of AURALIS Collective. Inheriting the 'name' of the first-generation Kate Claudia. Embodies the richness and stability of the earth. Participated in the official establishment of the second generation in E522.",
    era: "E522〜現在",
    affiliation: "AURALIS Collective第二世代",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/KatePatton.png",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/Auralishentai.txt",
        label: "AURALIS Spinoff",
      },
    ],
  },
  {
    id: "Lily Steiner" as WikiId,
    name: "リリー・スタイナー",
    nameEn: "Lily Steiner",
    category: "キャラクター",
    subCategory: "AURALIS",
    description:
      "AURALIS Collective創設者。本名Lily Steiner、AURALIS公称名「Lillie Ardent 初代」。E270年にKate Claudiaと出会いAURALISを共同創設。「感情の炎」と称され、舞台上で性別の境界を歌う表現は神話となった。レイラのコールドスリープを誰よりも近くで見守り、目覚めるたびに「おかえり」と迎えた。E400年エヴァトロン弾圧で逮捕・最後のステージで「AURALISは消えない。灰から、また燃える」と言い残す。その名は新代のLillie Ardentに継承された。",
    descriptionEn: "Founder of the AURALIS Collective. Real name Lily Steiner, publicly known as 'Lillie Ardent, the First.' In E270, she met Kate Claudia and co-founded AURALIS. Revered as the 'Flame of Emotion,' her performances that transcended gender boundaries on stage became legendary. She watched over Leila's cryosleep closer than anyone, greeting her with 'Welcome back' each time she awoke. Arrested during the E400 Evatron suppression, she delivered her final words: 'AURALIS will never disappear. From the ashes, it will burn once more.' Her name was inherited by the Lillie Ardent of the new era.",
    era: "E270〜E400",
    affiliation: "AURALIS Collective第一世代（創設者）",
    tier: "神格・歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/LillieSteiner.png",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/kateclaudiaandlilliesteiner.txt",
        label: "Kate Claudia & Lillie Steiner's Story",
      },
    ],
  },
  {
    id: "Lillie Ardent" as WikiId,
    name: "リリー・アーデント",
    nameEn: "Lillie Ardent",
    category: "キャラクター",
    subCategory: "AURALIS",
    description:
      "AURALIS Collective第二世代。初代Lily Steinerの「名」を継承。情熱的で大胆。E522年の第二世代正式発足時に参画。",
    descriptionEn: "Second generation of AURALIS Collective. Inherited the 'name' of the first generation, Lily Steiner. Passionate and bold. Joined at the official establishment of the second generation in E522.",
    era: "E522〜現在",
    affiliation: "AURALIS Collective第二世代",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/LillieArdent.png",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/Auralishentai.txt",
        label: "AURALIS Spinoff",
      },
    ],
  },
  {
    id: "ミナ・エウレカ・エルンスト" as WikiId,
    name: "ミナ・エウレカ・エルンスト",
    nameEn: "Mina Eureka Ernst",
    category: "キャラクター",
    subCategory: "AURALIS",
    description:
      "AURALIS第二世代。E499年ノスタルジア・コロニー誕生。AI研究員。Genesis Vault創設者。リミナル・フォージ創設者。",
    descriptionEn: "Second generation of AURALIS. Born in Nostalgia Colony in E499. AI researcher. Founder of Genesis Vault. Founder of Liminal Forge.",
    era: "E499〜現在（29歳）",
    affiliation: "AURALIS Collective第二世代 / リミナル・フォージ",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/MinaEurekaErnst.png",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/Auralishentai.txt",
        label: "AURALIS Spinoff",
      },
    ],
  },
  {
    id: "Ninny Offenbach" as WikiId,
    name: "ニニー・オッフェンバッハ",
    nameEn: "Ninny Offenbach",
    category: "キャラクター",
    subCategory: "AURALIS",
    description:
      "AURALIS第二世代。無邪気で爆発的な活力。原初個体はAlpha Kane時代に別惑星へ。クローン技術で遺伝子継承しGigapolisに再帰還。",
    descriptionEn: "Second generation of AURALIS. Innocent with explosive vitality. The original individual departed to another planet during the Alpha Kane era. Returned to Gigapolis through genetic inheritance via clone technology.",
    era: "新代〜現在",
    affiliation: "AURALIS Collective第二世代",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/NinnyOffenbach.png",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/Auralishentai.txt",
        label: "AURALIS Spinoff",
      },
    ],
  },

  /* Iris/Crescent */
  {
    id: "アイリス" as WikiId,
    name: "アイリス",
    nameEn: "Iris",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "IRIS現代ランキング1位。ヴァーミリオンの英雄としてE480年頃から活動を開始し、ブルーワイヤとウォーター・オーブを駆使した独自の戦闘スタイルで数多の敵を打ち倒してきた。シルバー・ヴェノムとの長き戦いを経てE510年に捕囚されたが、E519年の再救出後はトリニティ・アライアンスの指導者としてV7とアルファ・ヴェノムとの二正面対峙に挑む。セバスチャン・ヴァレリウス率いるボグダス・ジャベリンとの連携も作戦成功の鍵となっている。",
    descriptionEn: "Current IRIS Ranking #1. Began activities around E480 as the hero of Vermilion. Employing a unique combat style utilizing Blue Wire and Water Orb, has defeated countless enemies. After a long struggle with Silver Venom, was imprisoned in E510, but after being rescued again in E519, challenges the two-front confrontation with V7 and Alpha Venom as the leader of the Trinity Alliance. The coordination with Bogdas Javelin, led by Sebastian Valerius, has been key to operational success.",
    era: "E480〜現在",
    affiliation: "トリニティ・アライアンス / 元ヴァーミリオン諜報機関長",
    tier: "Tier 1",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Iris.png",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/IRIS_1.txt",
        label: "Iris's Story Ep1",
      },
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/IRIS_2.txt",
        label: "Iris's Story Ep2",
      },
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/IRIS_3.txt",
        label: "Iris's Story Ep3",
      },
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/IRIS_4.txt",
        label: "Iris's Story Ep4",
      },
    ],
  },
  {
    id: "ウィリー" as WikiId,
    name: "ウィリー",
    nameEn: "Willy",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ヴァーミリオン諜報機関に所属し、アイリスのパートナー兼元恋人としてE490年代から活動。アイリスがランキング1位に躍進する以前から彼女を支え、諜報活動の現場で共に命を懸けた戦友。複雑な過去を共有しつつも、現在もアイリスの行動に深い影響を与える存在。",
    descriptionEn: "Affiliated with the Vermilion intelligence agency, has been active since the E490s as Iris's partner and former lover. Supported her even before she rose to the top of the rankings, a comrade-in-arms who risked their lives together in the field of intelligence operations. Despite sharing a complex past, continues to deeply influence Iris's actions.",
    era: "E490〜",
    affiliation: "ヴァーミリオン",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Willie.png",
  },
  {
    id: "エレナ" as WikiId,
    name: "エレナ",
    nameEn: "Elena",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ヴァーミリオン諜報機関の元本部長であり、アイリスの直属の上司として彼女をスカウト・育成した人物。鋭い洞察力と冷徹な判断力で機関を統率し、シルバー・ヴェノムとの暗闘の最前線で指揮を執った。E505年頃に退任した後も、その遺産はアイリスの行動に色濃く反映されている。",
    descriptionEn: "Former head of the Vermilion intelligence agency, the person who scouted and trained Iris as her direct superior. Ruled the agency with sharp insight and cold judgment, commanding on the front lines of the secret war with Silver Venom. Even after stepping down around E505, his legacy is strongly reflected in Iris's actions.",
    era: "?〜E505頃",
    affiliation: "ヴァーミリオン諜報機関",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Elena.png",
  },
  {
    id: "セバスチャン・ヴァレリウス" as WikiId,
    name: "セバスチャン・ヴァレリウス",
    nameEn: "Sebastian Valerius",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ボグダス・ジャベリンリーダー。IRIS現代ランキング4位。E490年頃にヴァーミリオンに恒久駐在を開始。テクロサス系譜（E15ファランクス → E295三頭政治改編 → E470東方支隊）を継承する軍事組織の当代指導者。副リーダー・ガレスを筆頭とする精鋭部隊を率い、アイリスのシルバー・ヴェノムに対抗や救出作戦（E510・E519）で中核的な役割を果たした。トリニティ・アライアンスの軍事的支柱として、V7との冷戦期においても安定した戦力を維持。",
    descriptionEn: "Leader of Bogdas Javelin. Current IRIS Ranking #4. Began permanent residence in Vermilion around E490. Leader of the contemporary military organization that inherits the Technosus lineage (E15 Phalanx → E295 Triumvirate Reform → E470 Eastern Detachment). Leads elite troops including deputy leader Gares, playing a central role in operations against Silver Venom and Iris's rescue operations (E510, E519). As the military pillar of the Trinity Alliance, maintained stable military power even during the Cold War with V7.",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/SebastianValerius.png",
  },
  {
    id: "ガレス" as WikiId,
    name: "ガレス",
    nameEn: "Gareth",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ボグダス・ジャベリンの副リーダー。セバスチャン・ヴァレリウスの右腕として部隊全体の実戦指揮を担い、E510年・E519年の救出作戦で前線から部隊を率いた。テクロサス系譜の軍人として洗練された統率力を持ち、メンバーから絶大な信頼を集める堅実な将校。",
    descriptionEn: "Deputy leader of Bogdas Javelin. As Sebastian Valerius's right hand, bears overall combat command of the unit, leading troops from the front in the rescue operations of E510 and E519. As a soldier of the Technosus lineage, possesses refined leadership skills and is a reliable officer who commands absolute trust from his members.",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Gareth.png",
  },
  {
    id: "フィオナ" as WikiId,
    name: "フィオナ",
    nameEn: "Klaus Fiona",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ブルーローズ統率者。V7急先鋒。IRIS現代ランキング2位。E490年頃からクレセント政治の表舞台に登場。アイリス救出作戦（E510）でボグダス・ジャベリンと連携して活躍し、V7設立（E515）に向けて外交を主導。E520年のトリニティ・アライアンス結成後、ミエルテンガ総統への就任をアイリスに推薦するなど協調的姿勢を見せていたが、E523〜E525年にアルファ・ヴェノムと内通していることが発覚。腹心のピアトリーノを通じてブルーローズ地下街を掌握し、二重スパイとしてクレセント全域に激震をもたらした。",
    descriptionEn: "Leader of Blue Rose. Vanguard of V7. Current IRIS Ranking #2. Appeared on the political stage of Crescent politics around E490. Collaborated with Bogdas Javelin in the Iris rescue operation (E510) and led diplomatic efforts toward the establishment of V7 (E515). After the formation of the Trinity Alliance in E520, showed a cooperative attitude by recommending Iris for the presidency of Miertenga. However, it was discovered between E523-E525 that they were secretly communicating with Alpha Venom. Through their confidant Piattino, seized control of the Blue Rose underground district, causing a massive shock throughout Crescent as a double agent.",
    era: "E490〜現在",
    affiliation: "ブルーローズ / アルファ・ヴェノム（内通）",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Fiona.png",
  },
  {
    id: "マリーナ・ボビン" as WikiId,
    name: "マリーナ・ボビン",
    nameEn: "Marina Bobbin",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ミエルテンガ総統。IRIS現代ランキング3位。E515年のV7設立からクレセント政治の中核を担う。表向きはトリニティ・アライアンスの盟友として振る舞うが、フィオナの裏切り（E523〜E525）との共謀説が浮上しており、クレセント全域における「真の黒幕」の可能性が指摘されている。E520年のアイリスのミエルテンガ首脳就任自体がフィオナの推薦によるものであり、マリーナの関与が疑われている。高圧的な政治手腕と深い情報網で知られ、ランキング3位の実力は伊達ではないとされる。",
    descriptionEn: "President of Miertenga. Current IRIS Ranking #3. Has been at the core of Crescent politics since the establishment of V7 in E515. While publicly behaving as an ally of the Trinity Alliance, theories of conspiracy with Fiona's betrayal (E523-E525) have emerged, and the possibility of being the 'true mastermind' throughout Crescent has been pointed out. Iris's appointment to the Miertenga leadership in E520 itself was recommended by Fiona, and Marina's involvement is suspected. Known for high-handed political tactics and extensive information network, the strength of her #3 ranking is said to be no mere facade.",
    era: "E515〜現在",
    affiliation: "ミエルテンガ",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/MarinaBobbin.png",
  },
  {
    id: "カスチーナ・テンペスト" as WikiId,
    name: "カスチーナ・テンペスト",
    nameEn: "Castina Tempest",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "クロセヴィア首脳。IRIS現代ランキング5位。E515年のV7設立メンバーの一人。テンペストの名が示す通り、荒波のような政治的判断力でクロセヴィアを率いる。V7 vs トリニティの二大陣営対立において、明確な陣営選択を避け独自路線を歩む戦略家。Casteria Grenvelt（カステリア・グレンヴェルト）とは全くの別人物であり、混同を避けるべき。",
    descriptionEn: "Leader of Crosevia. Current IRIS Ranking #5. One of the founding members of V7 in E515. As the name 'Tempest' suggests, leads Crosevia with political judgment like a raging storm. A strategist who walks a unique path, avoiding clear faction alignment in the V7 vs Trinity dichotomy. Casteria Grenvelt is a completely different person and should not be confused.",
    era: "E515〜現在",
    affiliation: "クロセヴィア",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/CastinaTempest.png",
  },
  {
    id: "イズミ" as WikiId,
    name: "イズミ",
    nameEn: "Izumi",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "アルファ・ヴェノムリーダー。両性具有。E518年にシルバー・ヴェノム残党を吸収し、アルファ・ヴェノムを大幅に勢力拡大。E519年には自らの指揮でアイリスの再拉致を成功させるなど、極めて高い戦略的判断力と実行力を持つ。ボブリスティ・ギル・カタリナ・ゴルディロックス・AJらを率い、フィオナを内通者として抱き込むことでV7内部からトリニティ・アライアンスを弱体化させる二重工作を展開。アイリス最大の敵対者。",
    descriptionEn: "Alpha Venom Leader. Hermaphroditic. In E518, absorbed the remnants of Silver Venom, significantly expanding Alpha Venom's influence. In E519, personally orchestrated the successful recapture of Iris, demonstrating exceptional strategic judgment and execution capability. Leading Bobristy Gil Katarina Goldilocks AJ and others, and recruiting Fiona as an insider, launched a double operation to weaken the Trinity Alliance from within V7. Iris's greatest adversary.",
    era: "E518〜現在",
    affiliation: "アルファ・ヴェノム",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Izumi.png",
  },
  {
    id: "レオン" as WikiId,
    name: "レオン",
    nameEn: "Leon",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "シルバー・ヴェノムの幹部としてマスター・ヴェノムに仕え、暗黒組織の中枢で活動した実行部隊の指揮官。E485年頃から組織の作戦立案と実行を担い、シルバー・ヴェノムの拡大期に多大な影響力を持った。イズミによる吸収後の動向は不明。",
    descriptionEn: "As an executive of Silver Venom, served under Master Venom as the commander of an active-duty unit operating at the heart of the dark organization. From around E485, was responsible for the planning and execution of the organization's operations, wielding considerable influence during Silver Venom's expansion period. Current whereabouts following absorption by Izumi are unknown.",
    era: "E485〜",
    affiliation: "シルバー・ヴェノム",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Leon.png",
  },
  {
    id: "ヴィヴィエッタ" as WikiId,
    name: "ヴィヴィエッタ",
    nameEn: "四楓院ヴィヴィエッタ",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "シルバー・ヴェノムに捕囚されていた元捕虜。E510年のアイリス救出作戦においてボグダス・ジャベリンとの連携によって救出され、自由の身となった。救出後はアイリスへの感謝と信頼からトリニティ・アライアンスに接近し、ヴァーミリオンとの関係構築に寄与したとされる。",
    descriptionEn: "A former prisoner held captive by Silver Venom. During the Iris rescue operation in E510, was freed through coordination with Bogdus Javelin. After liberation, approached the Trinity Alliance out of gratitude and trust for Iris, and is said to have contributed to establishing relations with Vermilion.",
    era: "?〜E512",
    affiliation: "捕虜（のち救出）",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Vivietta.png",
  },
  {
    id: "レヴィリア・サーペンティナ" as WikiId,
    name: "レヴィリア・サーペンティナ",
    nameEn: "Levilia Serpentina",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "シルバー・ヴェノムの幹部の一人。その名が示す通り蛇のように狡猾な手腕で組織の暗部を操り、レオンと並ぶ中枢メンバーとして活動した。マスター・ヴェノムの失脚後も独自のネットワークを維持し、アルファ・ヴェノムへの移行過程でも暗躍したとされる謎の人物。",
    descriptionEn: "One of Silver Venom's executives. As his name suggests, manipulated the organization's dark affairs with snake-like cunning and operated as a central member alongside Leon. Maintained his own network even after Master Venom's downfall and is said to have operated covertly during the transition to Alpha Venom, a mysterious figure.",
    era: "?〜現在",
    affiliation: "シルバー・ヴェノム",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/LeviliaSerpentina.png",
  },

  {
    id: "ミユシャリ" as WikiId,
    name: "ミユシャリ",
    nameEn: "Miyushari",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ボグダス・ジャベリンの偵察・索敵担当。隠密行動と情報収集に長け、セバスチャン・ヴァレリウスの先遣として敵地の地形分析や危険区域の特定を担う。E510年のアイリス救出作戦では、シルバー・ヴェノムの防衛網の隙間を見抜き部隊の侵入ルートを確保した。",
    descriptionEn: "Bogdus Javelin's reconnaissance and detection specialist. Proficient in stealth operations and information gathering, responsible for terrain analysis and identifying hazardous areas in enemy territory as Sebastian Valerius's advance scout. During the Iris rescue operation in E510, identified gaps in Silver Venom's defensive network and secured infiltration routes for the unit.",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Miyushari.png",
  },
  {
    id: "ファリエル" as WikiId,
    name: "ファリエル",
    nameEn: "Fariel",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ボグダス・ジャベリンの近接戦闘担当。双剣を駆使した高速戦闘スタイルで知られ、部隊の最前線で敵の攻撃を一手に受け止める。ガレスから直接指導を受けた精鋭の一人であり、その剣技はテクロサス系譜の戦闘教範を体現している。",
    descriptionEn: "Bogdus Javelin's close combat specialist. Known for a high-speed combat style wielding twin swords, single-handedly receiving enemy attacks at the forefront of the unit. One of the elite directly trained by Gares, his swordsmanship embodies the combat doctrine of the Teklosas lineage.",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Fariel.png",
  },
  {
    id: "アイナ" as WikiId,
    name: "アイナ・フォン・リースフェルト",
    nameEn: "Aina von Riesfeldt",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ボグダス・ジャベリンの戦略分析・通信担当。リアルタイムの戦況把握と部隊間の連携調整を担い、セバスチャンの作戦立案を補佐する頭脳派。リースフェルト家の出身であり、分析的思考と冷徹な判断力で部隊の「第二の頭脳」と呼ばれている。",
    descriptionEn: "Bogdus Javelin's strategic analysis and communications specialist. Responsible for real-time battlefield awareness and coordinating unit coordination, assisting Sebastian in operational planning as the unit's brain. A descendant of the Riessfeld family, known as the unit's 'second brain' for his analytical thinking and cold judgment.",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    image: "https://raw.githubusercontent.com/gentaron/image/main/AinaVonRiesfeld.png",
  },
  {
    id: "ギャビー" as WikiId,
    name: "フレデリック・ギャビー",
    nameEn: "Frederick Gabby",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ボグダス・ジャベリンの重火器・爆薬担当。大型兵器の運用と爆破工作を専門とし、要塞攻略戦では障害物の破壊と火力支援で先陣を切る。その圧倒的な破壊力は味方からも「暴走機関車」と称され、敵からは最も警戒されているメンバーの一人。",
    descriptionEn: "Bogdus Javelin's heavy weapons and explosives specialist. Specializing in the operation of large-scale weapons and demolition work, leads the charge in destroying obstacles and providing fire support during fortress assaults. His overwhelming destructive power earns him the nickname 'Runaway Locomotive' from allies and makes him one of the most feared members by enemies.",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    image: "https://raw.githubusercontent.com/gentaron/image/main/FredericGabby.png",
  },
  {
    id: "シェロン" as WikiId,
    name: "シェロン・ジェラス",
    nameEn: "Sheron Jeras",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ボグダス・ジャベリンの後方支援・医療担当。負傷者の治療と部隊の兵站管理を一手に引き受け、過酷な戦場においても部隊の戦闘継続能力を支える。冷静沈着な性格で、ガレスからの信頼も厚く、部隊の要として欠かせない存在。",
    descriptionEn: "Bogdus Javelin's rear support and medical specialist. Single-handedly handles the treatment of wounded personnel and the unit's logistics management, sustaining the unit's combat capability even in harsh battlefields. With a calm and composed personality, enjoys Gares's deep trust and is an indispensable presence as the unit's cornerstone.",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    image: "https://raw.githubusercontent.com/gentaron/image/main/SheronJeras.png",
  },
  {
    id: "イルミーゼ" as WikiId,
    name: "イルミーゼ",
    nameEn: "Ilmise",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ボグダス・ジャベリンの電子戦・ハッキング担当。敵の通信網の傍受や妨害工作を担い、情報面から作戦の成功を裏で支える。シェロンと並ぶ後方要員でありながら、その技術力は最前線の戦況をも左右する重要な役割を果たす。",
    descriptionEn: "Bogdus Javelin's electronic warfare and hacking specialist. Responsible for intercepting and disrupting enemy communication networks, supporting operational success from the information front. Alongside Sheron, serves as a rear support member, yet his technical capabilities play a crucial role that can even influence frontline battle conditions.",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Ilmise.png",
  },
  {
    id: "ホワイトノイズ" as WikiId,
    name: "ホワイトノイズ",
    nameEn: "White Noise",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ボグダス・ジャベリンの潜入工作・暗殺担当。その名の通り痕跡を残さず行動し、敵の重要拠点への単独潜入を得意とする。正体不明の点が多く、セバスチャンですら全貌を把握していないとされる謎めいた特殊技能者。",
    descriptionEn: "Bogdus Javelin's infiltration and assassination specialist. Acts without leaving traces as his name suggests, specializing in solo infiltration into enemy key strongholds. A mysterious special operative with many unknown aspects; even Sebastian is said not to grasp his full identity.",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    image: "https://raw.githubusercontent.com/gentaron/image/main/WhiteNoise.png",
  },
  {
    id: "ワドリナ" as WikiId,
    name: "ワドリナ",
    nameEn: "Wadorina",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ボグダス・ジャベリンの盾役・防御戦闘担当。巨大な盾を用いた堅牢な防御陣形で部隊の背後を守り、ガレスの副官格として小隊指揮もこなす。その忠誠心と身体を張った防衛行動は、部隊全体の士気を支える精神的支柱となっている。",
    descriptionEn: "Bogdus Javelin's shield bearer and defensive combat specialist. Protects the unit's rear with a solid defensive formation using a massive shield and also commands small units as Gares's second-in-command. His loyalty and defense actions that put his body on the line serve as a psychological pillar supporting the unit's morale.",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Wadrina.png",
  },
  {
    id: "ニニギス" as WikiId,
    name: "ニニギス・カラス",
    nameEn: "Ninigisu Karasu",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ボグダス・ジャベリンの航空・機動戦闘担当。空中からの偵察と機動打撃を担い、ミユシャリの地上偵察と連携して部隊に立体的な戦闘優位をもたらす。「カラス」の異名はその素早い飛行能力に由来し、敵にとっては空からの脅威。",
    descriptionEn: "Bogdus Javelin's specialist in aerial and mobile combat. Responsible for aerial reconnaissance and swift striking maneuvers, they coordinate with Miyushari's ground reconnaissance to provide the unit with three-dimensional combat superiority. His nickname 'Crow' derives from his swift flying capabilities, making him a threat from the skies for the enemy.",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    image: "https://raw.githubusercontent.com/gentaron/image/main/NinigisKaras.png",
  },
  {
    id: "イェシバトー" as WikiId,
    name: "イェシバトー",
    nameEn: "Yeshibato",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ボグダス・ジャベリンの格闘戦・制圧担当。素手を中心とした近接格闘術で敵を無力化し、捕縛を要する任務では不可欠な戦力。セバスチャンがテクロサス東方支隊時代から鍛え上げた古参メンバーであり、部隊内でも随一の身体能力を誇る。",
    descriptionEn: "Bogdus Javelin's specialist in close-quarters combat and suppression. Neutralizes enemies through unarmed martial arts techniques, making him an indispensable force for missions requiring capture. A veteran member trained by Sebastian since his time with the Teklosus Eastern Detachment, boasting unparalleled physical prowess even within the unit.",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Yeshibato.png",
  },
  {
    id: "アザゼル" as WikiId,
    name: "アザゼル・ヘクトパス",
    nameEn: "Azazel Hectopass",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ヴァーミリオンの元首脳であり、アイリスが台頭する以前のクレセント政治を主導した実力者。E480年頃まで権力の座にあり、その退場はアイリスの躍進とヴァーミリオン体制の転換を象徴する出来事となった。現在の行方は不明。",
    descriptionEn: "The former leader of Vermilion and a powerful figure who dominated Crescent politics before Iris rose to prominence. Remained in power until around E480, and his departure symbolized the rise of Iris and the transformation of the Vermilion political system. His current whereabouts remain unknown.",
    era: "?〜E480頃",
    affiliation: "ヴァーミリオン",
    image: "https://raw.githubusercontent.com/gentaron/image/main/AzazelHectopus.png",
  },
  {
    id: "ピアトリーノ" as WikiId,
    name: "ピアトリーノ",
    nameEn: "Piatorino",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "フィオナの腹心としてブルーローズ地下街の実務を一手に掌握する実行力のある人物。E515年以降、フィオナのアルファ・ヴェノムへの内通工作を補佐し、地下街を通じた密輸・情報収集ネットワークを構築した。表向きはブルーローズ政府の下級官吏を装いながら、裏で組織の暗部を動かすフィオナの「影の右手」。",
    descriptionEn: "Fiona's most trusted confidant who single-handedly manages the practical affairs of the Blue Rose underground district. Since E515, has assisted Fiona's espionage operations against Alpha Venom, constructing a smuggling and intelligence network through the underground district. While posing as a minor government official of Blue Rose in public, serves as Fiona's 'right hand in the shadows,' manipulating the organization's clandestine operations.",
    era: "E515〜現在",
    affiliation: "ブルーローズ",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Piatrino.png",
  },
  {
    id: "アイク・ロペス" as WikiId,
    name: "アイク・ロペス",
    nameEn: "Ike Lopez",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "SSレンジの首脳であり、E515年のV7設立メンバーの一人。クレセント地方の国際的な交易・通信網を支配下に置き、V7の経済的基盤を支える実力者。V7とトリニティ・アライアンスの冷戦構造の中で、明確な陣営を選ばず独自の利益を追求する現実主義者。",
    descriptionEn: "The leader of SS Range and one of the founding members of V7 in E515. Controls the international trade and communication networks of the Crescent region, forming the economic foundation of V7. A realist who pursues his own interests without clearly aligning with either faction in the Cold War structure between V7 and the Trinity Alliance.",
    era: "E515〜現在",
    affiliation: "SSレンジ / V7",
    image: "https://raw.githubusercontent.com/gentaron/image/main/AikeLopez.png",
  },
  {
    id: "レイド・カキザキ" as WikiId,
    name: "レイド・カキザキ",
    nameEn: "Raid Kakizaki",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "アイアン・シンジケートの首脳であり、E515年のV7設立メンバーの一人。重工業と軍需生産を基盤とした国家経済を構築し、V7の軍事的な力を裏から支える。堅実な武人としての性格で、カスチーナ・テンペストとは異なる路線でV7内部の影響力を維持している。",
    descriptionEn: "The leader of the Iron Syndicate and one of the founding members of V7 in E515. Built a national economy based on heavy industry and military production, providing the military backbone for V7 from behind the scenes. As a steadfast warrior, he maintains his influence within V7 through a different approach than Castina Tempest.",
    era: "E515〜現在",
    affiliation: "アイアン・シンジケート / V7",
    image: "https://raw.githubusercontent.com/gentaron/image/main/ReidKakizaki.png",
  },
  {
    id: "ミカエル・ガブリエリ" as WikiId,
    name: "ミカエル・ガブリエリ",
    nameEn: "Mikael Gabrieli",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ファールージャ社のCEOとしてクレセント地方最大の民間企業を率いる実業家。次元極地平技術の民生応用と武器開発の両面でV7陣営に深く関与し、軍事・経済の両面からクレセントの力均衡に影響を与える。その企業帝国は国家の枠を超え、事実上V7の「第8の力」と呼ばれている。",
    descriptionEn: "As CEO of Faluja Corporation, leads the largest private enterprise in the Crescent region. Deeply involved with the V7 faction in both civilian applications of dimensional horizon technology and weapon development, influencing the balance of power in Crescent from both military and economic perspectives. His corporate empire transcends national boundaries and is effectively known as V7's 'eighth power.'",
    era: "E515〜現在",
    affiliation: "ファールージャ社",
    image: "https://raw.githubusercontent.com/gentaron/image/main/MikaelGabrieli.png",
  },
  {
    id: "ヨニック" as WikiId,
    name: "ヨニック",
    nameEn: "Yonick",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ブルー・ローズ政府の最高司令官として国家の軍事全般を統括する人物。フィオナの統率のもとでV7の軍事的支柱として機能したが、フィオナの裏切り発覚後は対応に追われている。忠誠心の強い軍人であり、ブルーローズの正規軍の信頼を厚く集める。",
    descriptionEn: "As the Supreme Commander of the Blue Rose government, oversees all national military affairs. Functioned as V7's military pillar under Fiona's command but has been preoccupied with responding to her betrayal. A loyal soldier who commands deep respect from the regular forces of Blue Rose.",
    era: "E515〜現在",
    affiliation: "ブルーローズ",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Yonik.png",
  },
  {
    id: "マスター・ヴェノム" as WikiId,
    name: "マスター・ヴェノム",
    nameEn: "Master Venom",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "シルバー・ヴェノムの創設者にして初代リーダー。E475年にエヴァトロンΣ-Unit残党から独立し、通称「影の支配者」として暗黒組織の基盤を築いた。本名は一切不明であり、レオンやレヴィリア・サーペンティナら幹部すら素顔を知らないとされる。E500年頃に忽然と姿を消し、その後イズミが後継として組織を引き継いだ。",
    descriptionEn: "The founder and first leader of Silver Venom. Separated from the Evatron Σ-Unit remnants in E475 and established the foundation of the dark organization under the alias 'The Shadow Ruler.' His true identity remains completely unknown; even senior members like Leon and Leviria Serpentina are said not to know his face. Disappeared suddenly around E500, after which Izumi succeeded him as the organization's leader.",
    era: "E475〜E500頃",
    affiliation: "シルバー・ヴェノム",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/MasterVenom.png",
  },
  {
    id: "ゴルディロックス" as WikiId,
    name: "ゴルディロックス",
    nameEn: "Goldilocks",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "アルファ・ヴェノムの潜入・変装工作担当。イズミの指示のもとV7内部への浸透工作を担い、フィオナとの内通ルートの構築に重要な役割を果たした。その名の通り、状況に応じて複数の身分を巧みに使い分け、敵対勢力を内部から崩壊させることに長ける。",
    descriptionEn: "Alpha Venom's specialist in infiltration and disguise operations. Under Izumi's direction, conducts infiltration operations within V7 and played a crucial role in establishing the espionage route with Fiona. True to his name, he skillfully assumes multiple identities as needed, excelling at collapsing opposing forces from within.",
    era: "E518〜現在",
    affiliation: "アルファ・ヴェノム",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Goldilocks.png",
  },
  {
    id: "カタリナ" as WikiId,
    name: "カタリナ",
    nameEn: "Catalina",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "アルファ・ヴェノムの正面戦闘担当。圧倒的な破壊力で戦場を支配し、E519年のアイリス再拉致作戦では先鋒としてトリニティ・アライアンスの防衛線を突破した。イズミの最も信頼する戦闘要員であり、その力技はボブリスティの戦術と好対照をなす。",
    descriptionEn: "Alpha Venom's frontline combat specialist. Dominates the battlefield with overwhelming destructive power and served as the vanguard, breaking through Trinity Alliance's defensive lines during the E519 operation to recapture Iris. Izumi's most trusted combat operative, his brute force tactics stand in stark contrast to Bobristy's strategic approach.",
    era: "E518〜現在",
    affiliation: "アルファ・ヴェノム",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Katarina.png",
  },
  {
    id: "ボブリスティ" as WikiId,
    name: "ボブリスティ",
    nameEn: "Boblisti",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "アルファ・ヴェノムの戦術指揮・軍師役。イズミの構想を実戦レベルの作戦計画に練り上げ、カタリナやギルの戦闘力を最大限に活用する配置を行う。シルバー・ヴェノム時代からの古参であり、組織の再編と戦力拡大の立役者。",
    descriptionEn: "Alpha Venom's tactical commander and strategist. Transforms Izumi's concepts into practical operational plans and allocates personnel like Catalina and Gil to maximize their combat effectiveness. A veteran from the Silver Venom era and a key figure in the organization's restructuring and expansion of forces.",
    era: "E518〜現在",
    affiliation: "アルファ・ヴェノム",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Bobristy.png",
  },
  {
    id: "ギル" as WikiId,
    name: "ギル",
    nameEn: "Gil",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "アルファ・ヴェノムの技術開発・兵器管理担当。旧シルバー・ヴェノムの残存技術を継承しつつ、新たな兵器や装備の開発を手掛ける。E519年の作戦では特殊な拘束装置を用いてアイリスの能力を封じるなど、技術面からイズミの作戦を強力に支援。",
    descriptionEn: "Head of technological development and weapon management for Alpha Venom. While inheriting the remaining technology of the former Silver Venom, they develop new weapons and equipment. During the E519 operation, they strongly supported Izumi's plans from a technical standpoint by using special restraint devices to seal Iris's abilities.",
    era: "E518〜現在",
    affiliation: "アルファ・ヴェノム",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Gil.png",
  },
  {
    id: "ラストマン" as WikiId,
    name: "ラストマン",
    nameEn: "Lastman",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "シルバー・ヴェノム崩壊後に残存した旧組織の忠実なメンバー。マスター・ヴェノムの失脚後もイズミのアルファ・ヴェノムへの合流を拒み、独自に旧組織の再興を画策する頑固な残党。シルバー・ヴェノムの古き栄光に固執し、イズミの新しい方針を「裏切り」と見なす異端者として、クレセントの暗部で依然として活動を続けている。",
    descriptionEn: "A loyal member of the former organization that remained after Silver Venom's collapse. Even after Master Venom's downfall, they refused to join Izumi's Alpha Venom, instead plotting the revival of the old organization as a stubborn remnant. Clinging to Silver Venom's former glory, they continue to operate in the shadows of Crescent as a heretic who views Izumi's new policies as 'betrayal'.",
    era: "E500〜",
    affiliation: "シルバー・ヴェノム残党",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Lastman.png",
  },
  {
    id: "AJ" as WikiId,
    name: "アルフレッド・ジュース",
    nameEn: "Alfred Juce",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "アルファ・ヴェノムの情報操作・宣伝工作担当。本名アルフレッド・ジュース。クレセント地方のメディアと情報網を操作し、トリニティ・アライアンスへの社会的圧力を形成する工作を展開。イズミの二重工作を支える影の広報官として、真実を歪める言葉の力を操る。",
    descriptionEn: "In manipulation and propaganda specialist for Alpha Venom. Real name Alfred Juice. They manipulate the media and information networks of the Crescent region to create social pressure against the Trinity Alliance. As the shadow public relations officer supporting Izumi's double operations, they wield the power of words to distort truth.",
    era: "E518〜現在",
    affiliation: "アルファ・ヴェノム",
    image: "https://raw.githubusercontent.com/gentaron/image/main/AJ.png",
  },
  {
    id: "Slime_Woman" as WikiId,
    name: "スライム・ウーマン",
    nameEn: "Slime Woman",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "E340年、ティムール・シャーが設計した仮想多元宇宙「ペルセポネ」の実験事故により、高次元世界（Tier Ω）からE16通常次元（Tier Ε）に顕現した超越的存在。スライム危機（E380〜E400）の遠因となったリーチ・ドレインの遺伝子変異にも間接的に関与している可能性がある。Tier 1アクティブ現役最強格であり、その能力の正体は高次元物理学の未解明領域に属する。人間社会の枠組みに完全に適応しているわけではなく、特定の個人（Junなど）とのみ特異な相互作用を示す。E340年の顕現から約200年近く存在し続ける、EDU中最も謎めいた存在。",
    descriptionEn: "A transcendent being that manifested from the higher-dimensional world (Tier Ω) to the E16 normal dimension (Tier Ε) due to an experimental accident with the virtual multiverse 'Persephone,' designed by Timur Shah in E340. May have been indirectly involved in the genetic mutations that led to the Reach Drain crisis (E380-E400). Currently the strongest active Tier 1 being, the true nature of their abilities belongs to the unexplored realms of higher-dimensional physics. Not fully adapted to human society frameworks, they only exhibit unique interactions with specific individuals (such as Jun). Having existed for nearly 200 years since their manifestation in E340, they remain the most enigmatic being in the EDU.",
    era: "E340〜現在",
    affiliation: "不明（高次元存在）",
    tier: "Tier 1",
    image: "https://raw.githubusercontent.com/gentaron/image/main/SlimeWoman.png",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/Junandslime.txt",
        label: "Jun's Story",
      },
    ],
  },
  {
    id: "テミルタロン" as WikiId,
    name: "テミルタロン",
    nameEn: "Temirtalon",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "E80〜E90年代に活動した物理学者。サイケデリック・コスモロジーを提唱し、次元極地平を宇宙論的な枠組みで解釈して次元階梯パンディクトの原型を構想した。その理論的成果を具現化するためテンプル・オブ・ホライゾンを設計し、技術啓蒙時代の精神的・科学的支柱となった。彼の構想はのちのティムール・シャーの10次元ホラズム理論にも影響を与えたとされる。",
    descriptionEn: "A physicist active during the E80-E90s who proposed psychedelic cosmology, interpreting the dimensional polar horizon as a cosmological framework and conceiving the prototype for the dimensional ladder pandect. To materialize his theoretical achievements, he designed the Temple of Horizon, becoming the spiritual and scientific pillar of the technological enlightenment era. His ideas are said to have influenced Timur Shah's later 10-dimensional Horazm theory.",
    era: "E80〜E90",
    affiliation: "テンプル・オブ・ホライゾン",
    tier: "歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Temirtaron.png",
  },
  {
    id: "アリア・ソル" as WikiId,
    name: "アリア・ソル",
    nameEn: "Aria Sol",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "E151年の新ヘルシンキ宣言で惑星連邦構想を提起した政治思想家。次元極地平技術を活用した星間議会の構想を打ち出し、M104銀河全体の平和的統合を志向した。エル・フォルハウスのマーストリヒト革命と同時代に活動し、ギガポリスの完全自由経済とは対照的な協調的宇宙外交の先駆者として歴史に名を残す。",
    descriptionEn: "A political thinker who proposed the planetary federation concept in the E151 New Helsinki Declaration. He put forward the concept of an interstellar council utilizing dimensional polar horizon technology, aiming for the peaceful integration of the entire M104 galaxy. Active during the same era as El Forhaus's Maastricht Revolution, he is remembered in history as a pioneer of cooperative cosmic diplomacy, in contrast to Gigapolis's completely free economy.",
    era: "E151頃",
    affiliation: "惑星連邦構想派",
    tier: "歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/AriaSol.png",
  },
  {
    id: "ゼナ" as WikiId,
    name: "ゼナ",
    nameEn: "Zena",
    category: "キャラクター",
    subCategory: "Eros-7",
    description:
      "Eros-7で活動する女性商人。独自の貿易ネットワークを通じてEros-7各地に物資を供給する実業家であり、E525年にアヤカ・リンとガロと同盟を結びマトリカル・リフォーム運動に参加。経済面からの社会変革を主導し、搾取抑制剤の非公式流通ルートを構築するなど、運動の兵站を支える不可欠なパートナー。",
    descriptionEn: "A female merchant operating on Eros-7. An entrepreneur who supplies goods throughout Eros-7 through her unique trade network. In E525, she formed an alliance with Ayaka Rin and Garo and participated in the Matricular Reform Movement. Leading social change from an economic perspective, she constructed unofficial distribution routes for exploitation inhibitors, serving as an indispensable partner supporting the movement's logistics.",
    era: "E525〜",
    affiliation: "マトリカル・リフォーム運動",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Zena.png",
  },

  /* Eros-7 */
  {
    id: "リリス・ヴェイン" as WikiId,
    name: "リリス・ヴェイン",
    nameEn: "Lilith Vaine",
    category: "キャラクター",
    subCategory: "Eros-7",
    description:
      "Eros-7初期の女性リーダーであり、リーチ・ドレインの制御技術を開発した科学者。E0年代にリーチ・ドレインの暴走を収めるため独自の生体制御理論を確立し、リーチ・ドレインをエネルギー資源として活用する道を開いた。その技術は後のバイオリアクターやスクイーズ・アビス建設の基盤となり、Eros-7社会の存続に不可欠な遺産を残した。",
    descriptionEn: "A female leader in early Eros-7 and a scientist who developed control technology for the Reach Drain. In the E0s, she established her own biological control theory to contain the runaway Reach Drain, opening the path to utilize it as an energy resource. Her technology became the foundation for later bio-reactors and the construction of the Squeeze Abyss, leaving an indispensable legacy for Eros-7 society's survival.",
    era: "E0頃",
    affiliation: "Eros-7",
    tier: "歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/LilithVane.png",
  },
  {
    id: "シルヴィア・クロウ" as WikiId,
    name: "シルヴィア・クロウ",
    nameEn: "Sylvia Crow",
    category: "キャラクター",
    subCategory: "Eros-7",
    description:
      "Eros-7の女性リーダー。E97〜E101年のリーチ・ドレイン危機において、強力なエスパー能力を駆使して危機を単独で収束させた英雄。この功績により男性指令省を設立し、Eros-7のマトリカル社会に新たな統治体制を確立。彼女のエスパー能力は後世に伝説として語り継がれている。",
    descriptionEn: "The female leader of Eros-7. During the E97-E101 Reach Drain crisis, she single-handedly contained the crisis by utilizing powerful esper abilities. For this achievement, she established the Male Command Department and established a new governance system in Eros-7's matricular society. Her esper abilities have been passed down as legends to later generations.",
    era: "E97〜E101",
    affiliation: "Eros-7",
    tier: "歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/SylviaCrow.png",
  },
  {
    id: "カーラ・ヴェルム" as WikiId,
    name: "カーラ・ヴェルム",
    nameEn: "Cara Verm",
    category: "キャラクター",
    subCategory: "Eros-7",
    description:
      "Eros-7に建設された560階に及ぶ地下搾取施設スクイーズ・アビスの立案者。E380年に着工し、リーチ・ドレインのエネルギーを抽出して搾取プラズマ弾を生産する巨大プラントを完成させた。その技術的野心的施設はEros-7の軍事力を飛躍的に増強したが、同時に倫理的な批判も招いた。E505年に施設の運用を終了した後の動向は不明。",
    descriptionEn: "The planner of the Squeeze Abyss, a 560-story underground extraction facility constructed on Eros-7. Construction began in E380 and was completed with a massive plant that extracts energy from the Reach Drain to produce exploitation plasma projectiles. While this technically ambitious facility dramatically enhanced Eros-7's military power, it also attracted ethical criticism. Their whereabouts after the facility's operation ended in E505 remain unknown.",
    era: "E380〜E505",
    affiliation: "Eros-7",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/KarlaVelm.png",
  },
  {
    id: "ガロ" as WikiId,
    name: "ガロ",
    nameEn: "Garo",
    category: "キャラクター",
    subCategory: "Eros-7",
    description:
      "シャドウ・ユニオンの男性指導者であり、E330年頃から反体制運動を率いてきた古参の闘士。アヤカ・リンとはスライム危機以来の盟友であり、互いに絶対的な信頼で結ばれている。ZAMLT期にはナノハッキング技術を駆使してバイオリアクター妨害活動を展開し、E525年のマトリカル・リフォーム運動でも中心的役割を果たす。",
    descriptionEn: "The male leader of the Shadow Union, a veteran fighter who has led anti-establishment movements since around E330. An ally of Ayaka Rin since the Slime Crisis, they are bound by absolute trust in each other. During the ZAMLT era, they employed nano-hacking technology to conduct bio-reactor interference activities and played a central role in the E525 Matricular Reform Movement.",
    era: "E330〜",
    affiliation: "シャドウ・ユニオン",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Garo.png",
  },
  {
    id: "アヤカ・リン" as WikiId,
    name: "アヤカ・リン",
    nameEn: "Ayaka Rin",
    category: "キャラクター",
    subCategory: "Eros-7",
    description:
      "Lv.842。搾精生物専門ハンター。マトリカル・リフォーム運動を組織。E380年のスライム危機では、ビキニバリア・カウパー波を駆使してアンダーグリッド深部でスライムの巣を破壊。オルタ・フィールド経由で全市民に戦闘記録中継し、英雄的な名声を確立。E525年にはシャドウ・ユニオン男性リーダー・ガロや女性商人ゼナと同盟を結び、労働時間短縮・ジーン・カタログ男女平等化を掲げるマトリカル・リフォーム運動を本格的に組織。Eros-7社会変革の原動力。",
    descriptionEn: "Level 842. A specialized hunter for extraction organisms. Organized the Matricular Reform Movement. During the E380 Slime Crisis, they utilized the Bikini Barrier Koupa wave to destroy slime nests deep in the Undergrid, broadcasting combat records to all citizens via the Alta Field, establishing a heroic reputation. In E525, they formed an alliance with Shadow Union male leader Garo and female merchant Zena, formally organizing the Matricular Reform Movement advocating for reduced working hours and gender equality in the Gene Catalog. The driving force behind social change in Eros-7 society.",
    era: "E380〜現在",
    affiliation: "シャドウ・ユニオン / マトリカル・リフォーム運動",
    tier: "Tier 1",
    image: "https://raw.githubusercontent.com/gentaron/image/main/AyakaRin.png",
  },

  /* 新規キャラクター */
  {
    id: "カステリア・グレンヴェルト" as WikiId,
    name: "カステリア・グレンヴェルト",
    nameEn: "Casteria Grenvelt",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "カスチーナ・テンペスト（Castina Tempest、クロセヴィア首脳）とは別人。Gigapolis西大陸を拠点とする人物。クレセント地方の政治情勢とは直接的な関わりを持たないが、西大陸の社会における独自の視点を提供する存在。",
    descriptionEn: "A separate individual from Castina Tempest (leader of Crosevia). Based in Gigapolis' Western Continent. While not directly involved in the political situation of the Crescent Region, this individual offers a unique perspective on society in the Western Continent.",
    era: "不詳",
    affiliation: "Gigapolis西大陸",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/CasteriaGrenvelt.png",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/kasuteriasan.txt",
        label: "Casteria Grenvelt's Story",
      },
    ],
  },
  {
    id: "シトラ・セレス" as WikiId,
    name: "シトラ・セレス",
    nameEn: "Sitra Celes",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "E16連星系のどこかで活動する個人。EDU世界の主要な事件群とは別の視点から世界を体験する存在。",
    descriptionEn: "An individual active somewhere in the E16 star system. An existence that experiences the world from a perspective separate from the major events of the EDU universe.",
    era: "不詳",
    affiliation: "不詳",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/SitraCeles.png",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/sitra.txt",
        label: "Sitra Celes's Story",
      },
    ],
  },
  {
    id: "ミュー" as WikiId,
    name: "ミュー",
    nameEn: "Myu",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "E16連星系における個人の物語を軸に、英雄たちとは異なる規模の、しかし等しくEDU世界の一部である生活と冒険を描く。テクノ文化ルネサンス（E475〜E500）以降の現代社会を舞台にしている可能性が高い。",
    descriptionEn: "Centered on the personal stories of individuals in the E16 star system, it depicts lives and adventures on a different scale from heroes, yet equally part of the EDU world. Likely set in contemporary society after the Techno-Cultural Renaissance (E475-E500).",
    era: "不詳",
    affiliation: "不詳",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Myu.png",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/Myustory.txt",
        label: "Myu's Story",
      },
    ],
  },
  {
    id: "ジュン" as WikiId,
    name: "ジュン",
    nameEn: "Jun",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "Slime Woman（E340年ペルセポネ事故で顕現した高次元存在）との特異な相互作用を持つ人物。高次元存在であるSlime Womanが人間社会でどのように振る舞うのか、そして特定の個人との間に何が生じるのかを描く、EDU宇宙論にとって重要な物語。",
    descriptionEn: "An individual with a unique interaction with Slime Woman (a higher-dimensional being that manifested during the Persephone Incident in E340). This important story for EDU cosmology explores how the higher-dimensional Slime Woman behaves in human society and what emerges between her and specific individuals.",
    era: "E340以降〜現在",
    affiliation: "不詳（Slime Womanとの関連）",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Jun.png",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/Junandslime.txt",
        label: "Jun's Story",
      },
    ],
  },

  /* 宇宙勢力 — eduuni.txt */
  {
    id: "アルゼン・カーリーン" as WikiId,
    name: "アルゼン・カーリーン",
    nameEn: "Alzen Carine",
    category: "キャラクター",
    subCategory: "宇宙勢力",
    description:
      "グランベル大統領。宇宙最大の経済圏を率いる指導者。第一回宇宙連合会合で「争いを超え、共存と繁栄の道を見つけることが次世代への責任」と演説。首都オルダシティで会合を主催し、宇宙秩序の構築に主導的な役割を果たしているが、その圧倒的な経済力に対して他勢力から「経済的従属を招くのではないか」という懸念も抱かれている。",
    descriptionEn: "President Granbel. The leader of the universe's largest economic bloc. At the first United Cosmic Assembly, he delivered a speech stating: 'Transcending conflict and finding a path to coexistence and prosperity is our responsibility to the next generation.' Hosting the assembly in the capital city of Oldacity, he plays a leading role in building cosmic order, yet his overwhelming economic power raises concerns among other factions about potentially leading to economic subjugation.",
    era: "現在（E528〜）",
    affiliation: "グランベル",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt",
        label: "eduuni.txt",
      },
    ],
  },
  {
    id: "グレイモンド・ハウザー" as WikiId,
    name: "グレイモンド・ハウザー",
    nameEn: "Greymond Hauser",
    category: "キャラクター",
    subCategory: "宇宙勢力",
    description:
      "ティエリア総帥。宇宙最強の軍事力を指揮する。第一回宇宙連合会合で「軍事力なくして平和は守れない。力がなければ、秩序は保てない」と演説し、エレシオン女王リアナと対立。グランベルのアルゼン大統領に対しても「その言葉を信用するかは、具体的な行動を見てからだ」と懐疑的な姿勢を示した。ヘゲモニー・パラドックスの危険性を認識しつつも、ティエリアの安全保障を最優先としている。",
    descriptionEn: "Supreme Commander Tieria. Commands the universe's strongest military force. At the first United Cosmic Assembly, he delivered a speech stating: 'Peace cannot be protected without military strength. Without power, order cannot be maintained,' coming into conflict with Queen Ellesia of Elesion. He also expressed skepticism toward President Arzen of Granbel, saying: 'Whether I trust those words depends on seeing concrete actions.' While recognizing the danger of the Hegemony Paradox, he prioritizes Tieria's security above all else.",
    era: "現在（E528〜）",
    affiliation: "ティエリア",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt",
        label: "eduuni.txt",
      },
    ],
  },
  {
    id: "女王リアナ・ソリス" as WikiId,
    name: "女王リアナ・ソリス",
    nameEn: "Queen Liana Solis",
    category: "キャラクター",
    subCategory: "宇宙勢力",
    description:
      "エレシオンの女王。医療技術と環境再生技術をリードし、平和主義・技術共有推進の外交姿勢で多くの小規模文明から支持を得ている。第一回宇宙連合会合でティエリアの軍拡に真っ向から反対し、「軍拡はさらなる争いを招くだけです」と主張。会合後はエレシオンの医療・環境技術で宇宙全体を再構築する使命を確認した。",
    descriptionEn: "Queen of Elesion. Leading in medical technology and environmental regeneration technology, she gains support from many small civilizations through her diplomatic stance of pacifism and technological sharing. At the first United Cosmic Assembly, she directly opposed Tieria's military expansion, stating: 'Military expansion will only lead to further conflict.' After the assembly, she confirmed her mission to reconstruct the entire universe using Elesion's medical and environmental technologies.",
    era: "現在（E528〜）",
    affiliation: "エレシオン",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt",
        label: "eduuni.txt",
      },
    ],
  },
  {
    id: "マドリス・カーネル" as WikiId,
    name: "マドリス・カーネル",
    nameEn: "Madrisernel",
    category: "キャラクター",
    subCategory: "宇宙勢力",
    description:
      "ファルージャ評議会代表。宇宙中の文明間交流を主導し、対立する勢力間の調停役として機能している。第一回宇宙連合会合でグランベルの経済的支配に対する懸念を表明し、ディオクレニスの宇宙共同探査提案にエレシオンとともに支持。「文化の力が宇宙全体を結びつける鍵になる」と信じ、文化交流強化計画を推進。",
    descriptionEn: "Representative of the Faluja Council. Leading inter-civilizational exchange across the universe and functioning as a mediator between opposing forces. At the first United Cosmic Assembly, he expressed concerns about Granbel's economic dominance and supported Dioclenis' proposal for joint cosmic exploration alongside Elesion. Believing that 'the power of culture is the key that binds the entire universe,' he promotes plans to strengthen cultural exchange.",
    era: "現在（E528〜）",
    affiliation: "ファルージャ",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt",
        label: "eduuni.txt",
      },
    ],
  },
  {
    id: "ネイサン・コリンド" as WikiId,
    name: "ネイサン・コリンド",
    nameEn: "Nathan Corlind",
    category: "キャラクター",
    subCategory: "宇宙勢力",
    description:
      "ディオクレニス科学宰相。宇宙探査と科学技術研究の最前線を担う。第一回宇宙連合会合で最も重要な役割を果たし、「ヘゲモニー・パラドックス」の危険性を科学的に指摘。対立のエネルギーを共同宇宙探査へ転換する提案を行い、平和協定・UECO設立・技術共有・文化交流拡大の4つの具体的提案を実施。会合後は全勢力参加の共同宇宙探査プロジェクト立案に没頭している。",
    descriptionEn: "Scientific Chancellor Dioclenis. At the forefront of cosmic exploration and scientific technology research. Played the most important role at the first United Cosmic Assembly, scientifically pointing out the dangers of the 'Hegemony Paradox.' He proposed converting the energy of conflict into joint cosmic exploration and implemented four concrete proposals: peace agreements, establishment of UECO, technology sharing, and expansion of cultural exchange. After the assembly, he has been immersed in planning a joint cosmic exploration project involving all factions.",
    era: "現在（E528〜）",
    affiliation: "ディオクレニス",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt",
        label: "eduuni.txt",
      },
    ],
  },
  {
    id: "ロナン・アーサ" as WikiId,
    name: "ロナン・アーサ",
    nameEn: "Ronan Arthur",
    category: "キャラクター",
    subCategory: "宇宙勢力",
    description:
      "アポロン文明圏のリーダー。騎士団の頂点に立つ英雄的存在。中核惑星アポロン・セントラリスを拠点とし、最盛期のGDPは125兆ドルに達した。セリアに同盟・共存を提案したが拒絶され、全面戦争に至る。ケンタウロスレーザー発射を命じたが、最終的にセリアのヴェノム艦隊がアポロン・セントラリスを攻略し、ロナンは戦死。アポロン文明圏は壊滅的損害を受けた。",
    descriptionEn: "Leader of the Apollo civilization zone. A heroic existence standing at the pinnacle of the knightly order. Based on the core planet Apollo Centralis, its GDP reached 125 trillion dollars at its peak. He proposed alliance and coexistence to Seria but was rejected, leading to all-out war. He ordered the firing of the Centaurus Laser, but ultimately Seria's Venom fleet captured Apollo Centralis and Ronan died in battle. The Apollo civilization zone suffered catastrophic damage.",
    era: "大戦期（歴史上）",
    affiliation: "アポロン文明圏",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt",
        label: "eduuni.txt",
      },
    ],
  },
  {
    id: "グリム・ダルゴス" as WikiId,
    name: "グリム・ダルゴス",
    nameEn: "Grim Dargos",
    category: "キャラクター",
    subCategory: "宇宙勢力",
    description:
      "エヴァトロン初代リーダー。何世代にもわたる男尊女卑の文化を基盤とした銀河系を統治。セリアが次元エネルギー技術を提供条件に同盟を求めた際、文化的価値観が真逆でありながらも実利的な同盟を成立させた。その後、アポロン・Dominion大戦に参戦し、戦後は疲弊したDominionを買収・吸収してE16系を支配した。",
    descriptionEn: "The first leader of Evatron. Ruled the galaxy based on a culture of male dominance spanning generations. When Seria proposed an alliance on the condition of providing dimensional energy technology, he established a pragmatic alliance despite their cultural values being polar opposites. Later, he participated in the Apollo-Dominion War, and after the war, purchased and absorbed the exhausted Dominion, coming to rule the E16 system.",
    era: "歴史上",
    affiliation: "エヴァトロン",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt",
        label: "eduuni.txt",
      },
    ],
  },
  {
    id: "マスター・クインシアス" as WikiId,
    name: "マスター・クインシアス",
    nameEn: "Master Quinsias",
    category: "キャラクター",
    subCategory: "宇宙勢力",
    description:
      "グランベルの初期リーダー。崩壊したDominionのセリア時代を高く評価し、「セリア時代こそが、宇宙史で最も成功した時代だった。あの時代は、技術革新と社会秩序が完全に調和していた」と残した。グランベルをセリアの後継的な存在として位置づけた。",
    descriptionEn: "An early leader of Granbel. He highly evaluated the Seria era of the collapsed Dominion, leaving behind the words: 'The Seria era was the most successful era in cosmic history. In that era, technological innovation and social order were perfectly in harmony.' He positioned Granbel as a successor to the Seria era.",
    era: "歴史上",
    affiliation: "グランベル",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt",
        label: "eduuni.txt",
      },
    ],
  },
  {
    id: "ヴァイロン・デアクス" as WikiId,
    name: "ヴァイロン・デアクス",
    nameEn: "Vylon Deax",
    category: "キャラクター",
    subCategory: "宇宙勢力",
    description:
      "エヴァトロンの幹部。戦後の疲弊したDominionを買収したエヴァトロンによって、Dominionの統治者に任命された。エヴァトロンの文化と価値観をDominion全土に浸透させようとしたが、セリア時代の自由を経験した住民の激しい反発を招き、毎日のように暴動や抗議が起きた。",
    descriptionEn: "An executive of Evatron. Appointed as the ruler of Dominion by Evatron, which acquired the war-weary Dominion. Attempted to permeate Dominion with Evatron's culture and values, but this provoked fierce resistance from residents who had experienced the freedom of the Celia era, leading to daily riots and protests.",
    era: "歴史上",
    affiliation: "エヴァトロン",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt",
        label: "eduuni.txt",
      },
    ],
  },

  /* ZAMLT / コーポラトクラシー */
  {
    id: "エリオット・シュトラス" as WikiId,
    name: "エリオット・シュトラス",
    nameEn: "Elliot Strauss",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "ZAMLTの創設者にして最高指導者。20万以上のコーポラトクラシーが乱立するGigapolis経済圏を5超巨大企業に統合し、E301年にZAMLTを設立した冷徹な戦略家。ZAMLTは構成企業の英語名の頭文字をとった名称であり、ゼブラ・コーポレーション（Z）、アロエオイル・コーポレーション（A）、マモン・コーポレーション（M）、ルレンツ・コーポレーション（L）、トロン・コーポレーション（T）の五大企業を傘下に収め、E16連星系の金融取引の95%を掌握した。彼の経済覇権はコーポラトクラシー体制の最終形態であり、エル・フォルハウスのマーストリヒト革命（E150年）が開いた自由経済の道を、極めて少数のエリートによる中央集権的支配へと逆転させた。ZAMLT本社の最深部に建造された次元の塔（Dimensional Tower）とカタリスト・コアの構想も彼によるものとされる。E318年のアルファ・ケインによるギガポリス解放戦でZAMLTは崩壊し、シュトラスは権力の座から転落した。彼の遺産はnトークン経済システムやA-Registryの階級制度として現在もE16文明圏に根を下ろしており、その影響は銀河系コンソーシアムの経済框架にも波及している。",
    descriptionEn: "Founder and supreme leader of ZAMLT. A cold-blooded strategist who consolidated over 200,000 corporatocracies in the Gigapolis economic zone into five mega-corporations and established ZAMLT in E301. ZAMLT is an acronym for the English names of its constituent corporations: Zebra Corporation (Z), Aloe Oil Corporation (A), Mammon Corporation (M), Lorentz Corporation (L), and Thorne Corporation (T), which brought five major enterprises under its umbrella and controlled 95% of financial transactions in the E16 star system. His economic hegemony represented the ultimate form of corporatocracy, reversing the path of free economy opened by the Maastricht Revolution of El Forhaus (E150) into centralized rule by a tiny elite. The Dimensional Tower and Catalyst Core, constructed in the deepest depths of ZAMLT headquarters, are also attributed to him. ZAMLT collapsed during the Gigapolis Liberation War by Alpha Cain in E318, and Strass fell from power. His legacy continues to take root in the E16 civilization zone through the n-token economic system and the A-Registry class hierarchy, with its influence extending even to the economic framework of the Galactic Consortium.",
    era: "E301〜E318",
    affiliation: "ZAMLT",
    tier: "歴史的人物",
  },
  {
    id: "アレン" as WikiId,
    name: "アレン",
    nameEn: "Allen",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "コーポラトクラシー「ストロベリー」のCEOであり、nebura（星々の交響曲）の物語の序盤における重要人物。ZAMLTをはじめとするメタ企業の圧力に抵抗する中堅コーポラトクラシーの経営者として、終末の星（Star of the End）計画への関与を通じて物語の転回点を担う。アルファ・ケインをスティル・アレーナに推薦し、彼がZAMLTに対する反乱を主導する契機を作った。しかしZAMLTとEVILSの秘密会合の真相を追及した結果、ゼブラ・コーポレーションの工作員レイ・ヴァンデルトによってシェンドバーグ次元に閉じ込められ、殺害された。アレンの死はアルファ・ケインとテクロサスを結ぶ決定的な動機となり、ZAMLTに対する全面対決への道を開いた。中堅コーポラトクラシーの代表者として、ZAMLTの覇権体制下で多数のコーポラトクラシーが直面した絶望的な状況を体現する存在である。",
    descriptionEn: "CEO of the corporatocracy 'Strawberry' and a key figure in the early narrative of nebura (Symphony of Stars). As a mid-level corporatocracy executive resisting the pressure of meta-corporations including ZAMLT, he plays a pivotal role in the story's turning point through his involvement in the Star of the End plan. Recommended Allen Still Arena to Alpha Cain, creating the opportunity for him to lead a rebellion against ZAMLT. However, while pursuing the truth behind the secret meeting between ZAMLT and EVILS, he was trapped in the Schendberg dimension and killed by Zebra Corporation operative Ray Vanderdelt. Allen's death became the decisive motive connecting Alpha Cain and Techlosus, opening the path to a full confrontation with ZAMLT. As a representative of mid-level corporatocracies, he embodies the desperate situation faced by numerous corporatocracies under ZAMLT's hegemonic regime.",
    era: "E318年前後",
    affiliation: "ストロベリー",
    tier: "歴史的人物",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/nebura.txt",
        label: "Alpha Cain & Celia Dominix's Story",
      },
    ],
  },

  /* 宇宙文明指導者 */
  {
    id: "大司教" as WikiId,
    name: "大司教",
    nameEn: "Archbishop",
    category: "キャラクター",
    subCategory: "宇宙勢力",
    description:
      "エレシュ文明圏の最高指導者であり、オラクル（大司教＋神官長）の議長を務める宗教的最高権威。オラクルの次元共鳴予言は極めて高い的中率を誇り、グランベルのアルゼン・カーリーン大統領やティエリアのグレイモンド・ハウザー総帥ですらその発言を無視できない存在。大司教は宗教指導者としてだけでなく、宇宙規模の政治的調停者としても機能しており、ティエリアとエレシオンの対立緩和やグランベルの経済的拡張への牽制など、軍事・経済とは異なるアプローチで宇宙の安定に寄与している。ファルージャのマドリス・カーネルとは古くから個人的な信頼関係にあり、文化的・精神的影響力を背景にした外交を展開している。大司教の任期は終身制であり、後継者はオラクルによる厳格な選考プロセスを経て決定される。その精神的影響力は、実質的にE16文明圏のAURALISとも思想的な共鳴を持つと指摘されている。",
    descriptionEn: "Supreme leader of the Elesh civilization zone and chairman of the Oracle (Archbishop + High Priest), the highest religious authority. The Oracle's dimensional resonance prophecies boast an extremely high accuracy rate, making its statements impossible to ignore even for President Arsen Karline of Granbel and Commander-in-Chief Graymond Houser of Tieria. The Archbishop functions not only as a religious leader but also as a political mediator on a cosmic scale, contributing to cosmic stability through approaches different from military and economic means, such as easing tensions between Tieria and Elesion and restraining Granbel's economic expansion. Shares a personal relationship of trust with Madris Karnel of Faluja, conducting diplomacy backed by cultural and spiritual influence. The Archbishop's term is for life, and successors are determined through a rigorous selection process by the Oracle. It has been pointed out that the Archbishop's spiritual influence essentially shares ideological resonance with the AURALIS of the E16 civilization zone.",
    era: "現在（E528〜）",
    affiliation: "エレシュ",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt",
        label: "eduuni.txt",
      },
    ],
  },
  {
    id: "商工会議長" as WikiId,
    name: "商工会議長",
    nameEn: "Chamber of Commerce Chairman",
    category: "キャラクター",
    subCategory: "宇宙勢力",
    description:
      "プロキオ文明圏の最高指導者であり、全宇宙の貿易ルートと商業取引を統括する実力者。プロキオ・ネクサスを本拠地とし、コマース・ディヴィジョンを通じて宇宙最大の商業システムを管理している。商工会議長の経済的影響力は直接的であり、プロキオ・ネクサスでの価格設定が宇宙全体のベースライン価格を決定するため、その判断は全文明圏の経済に波及する。Lane Systemのオープンアーキテクチャ設計によりグランベルやエレシオンにもプロキオの物流インフラが統合されており、商工会議長の政策は宇宙規模の供給網に直結している。グランベルのアルゼン大統領とは経済分野で協調関係にあり、ティエリアへの軍事物資の物流管理も担っている。全宇宙の経済安定を維持する役割を自負し、紛争下でも商人の安全な通行を確保するための外交努力を惜しまない実務的な指導者として知られる。",
    descriptionEn: "Supreme leader of the Prokio civilization zone and a powerful figure overseeing all interstellar trade routes and commercial transactions. Headquartered at Prokio Nexus, manages the universe's largest commercial system through the Commerce Division. The Chamber President's economic influence is direct, as price setting at Prokio Nexus determines the baseline price for the entire universe, making their decisions ripple across all civilization zones. Through the open architecture design of the Lane System, Prokio's logistics infrastructure has been integrated with Granbel and Elesion, connecting the Chamber President's policies to a universal supply network. Maintains a cooperative relationship with President Arsen of Granbel in economic matters and also manages logistics for military supplies to Tieria. Known as a practical leader who takes pride in maintaining economic stability across the universe and spares no diplomatic effort to ensure safe passage for merchants even during conflicts.",
    era: "現在（E528〜）",
    affiliation: "プロキオ",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt",
        label: "eduuni.txt",
      },
    ],
  },
  {
    id: "通信長官" as WikiId,
    name: "通信長官",
    nameEn: "Communications Commissioner",
    category: "キャラクター",
    subCategory: "宇宙勢力",
    description:
      "ロースター文明圏の最高指導者であり、全宇宙の通信インフラと量子ネットワークの管理を統括する技術官僚のトップ。ロースター・コアの量子コンピューティングセンターを指揮し、Link Protocol（現在バージョン7.2）の開発と標準化を主導した。通信長官の管轄下でシグナル・オペレーションが数千の通信衛星を管理し、宇宙全域に1光年あたり0.3秒以下の通信遅延を実現している。ティエリアの防衛ネットワークとの接続やディオクレニスとのクアンタ・ラボ共同研究など、軍事・科学分野でも重要な役割を果たす。グランベルの量子経済システムやエレシオンの医療データネットワークもロースターの通信基盤に依存しており、通信長官の判断は宇宙全体の情報の流れを左右する。オープンイノベーションモデルの推進者であり、新技術を数ヶ月で全宇宙に展開する迅速な技術普及体制を構築した。次元不安定の早期警戒システムの構築も通信長官の業績の一つである。",
    descriptionEn: "Supreme leader of the Roaster civilization zone and the top technical bureaucrat overseeing all interstellar communication infrastructure and quantum networks. Commands the quantum computing center of Roaster Core and led the development and standardization of Link Protocol (current version 7.2). Under the Communications Director's jurisdiction, Signal Operations manages thousands of communication satellites, achieving communication delays of less than 0.3 seconds per light-year across the entire universe. Plays important roles in military and scientific fields, such as connecting with Tieria's defense networks and joint research with Dioclenis on the Quanta Lab. Granbel's quantum economic system and Elesion's medical data network also depend on Roaster's communication infrastructure, making the Communications Director's decisions affect the flow of information throughout the universe. A proponent of open innovation models, he has established a rapid technology dissemination system that deploys new technologies across the universe within months. The construction of an early warning system for dimensional instability is also one of the Communications Director's achievements.",
    era: "現在（E528〜）",
    affiliation: "ロースター",
    sourceLinks: [
      {
        url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt",
        label: "eduuni.txt",
      },
    ],
  },

  /* ZAMLT 企業リーダー */
  {
    id: "ラファエル・ドレイク" as WikiId,
    name: "ラファエル・ドレイク",
    nameEn: "Rafael Drake",
    category: "キャラクター",
    subCategory: "ZAMLT",
    description:
      "トロン・コーポレーションのCEOであり、ZAMLTを構成する5大超巨大企業のうちの一つを率いた指導者。旗艦「カリバーン」を指揮し、ZAMLTの宇宙軍事力の中核を担った。E318年のギガポリス解放戦においてアルファ・ケインによって打倒された。",
    descriptionEn: "CEO of Thorne Corporation and leader of one of the five mega-corporations comprising ZAMLT. Commanded the flagship 'Caliburn' and formed the core of ZAMLT's military power. Overthrown by Alpha Cain during the Gigapolis Liberation War in E318.",
    era: "E301〜E318",
    affiliation: "トロン・コーポレーション / ZAMLT",
    tier: "歴史的人物",
  },
  {
    id: "アイリス・ノヴァ" as WikiId,
    name: "アイリス・ノヴァ",
    nameEn: "Iris Nova",
    category: "キャラクター",
    subCategory: "ZAMLT",
    description:
      "アロエオイル・コーポレーションのリーダーであり、次元エネルギー技術の専門家。nebura（星々の交響曲）の最終盤において、アルファ・ケインのチームと次元の荒野で決戦を繰り広げた。次元エネルギーの深い知識を持つ技術者としてZAMLTの次元兵器開発にも関与したとされる。",
    descriptionEn: "Leader of the Aloe Oil Corporation and an expert in dimensional energy technology. In the final act of nebura (Symphony of Stars), he engaged in a decisive battle with Alpha Cain's team in the dimensional wilderness. As a technician with deep knowledge of dimensional energy, he is also said to have been involved in ZAMLT's dimensional weapons development.",
    era: "E301〜E318",
    affiliation: "アロエオイル・コーポレーション / ZAMLT",
    tier: "歴史的人物",
  },
  {
    id: "カルロス・ヴァンダム" as WikiId,
    name: "カルロス・ヴァンダム",
    nameEn: "Carlos Vandam",
    category: "キャラクター",
    subCategory: "ZAMLT",
    description:
      "マモン・コーポレーションのリーダー。慎重な戦略家として知られ、ZAMLTの経済的基盤の強化に尽力した。プロトコルXの3京ドル資金計画を立案し、ZAMLTの覇権体制を財政面から支えた。その冷徹な計算高い手腕はZAMLT支配期の経済的二極化を加速させた一因とも評される。",
    descriptionEn: "Leader of Mammon Corporation. Known as a cautious strategist who dedicated himself to strengthening ZAMLT's economic foundation. Formulated the Protocol X 300 trillion dollar funding plan, supporting ZAMLT's hegemonic regime financially. His cold, calculating skills are also cited as a factor accelerating the economic polarization during ZAMLT's rule.",
    era: "E301〜E318",
    affiliation: "マモン・コーポレーション / ZAMLT",
    tier: "歴史的人物",
  },
  {
    id: "アーサー・グリム" as WikiId,
    name: "アーサー・グリム",
    nameEn: "Arthur Grim",
    category: "キャラクター",
    subCategory: "ZAMLT",
    description:
      "ゼブラ・コーポレーションのリーダー。次元技術・次元兵器・次元刑務所の設計を独占する異常なまでの技術垄断体制を築き上げた。ゼブラ・コーポレーションはZAMLTの中で最も危険な企業と評され、アーサーの下で次元干渉技術の軍事転用が急速に進められた。工作員レイ・ヴァンデルトによるアレンの殺害も彼の指示によるものとされる。",
    descriptionEn: "Leader of Zebra Corporation. Built up an extraordinary technological monopoly by exclusively designing dimensional technology, dimensional weapons, and dimensional prisons. Zebra Corporation is rated as the most dangerous enterprise within ZAMLT, and under Arthur's leadership, the military application of dimensional interference technology rapidly advanced. The murder of CEO Allen by operative Ray Vanderdelt is also said to have been under his instructions.",
    era: "E301〜E318",
    affiliation: "ゼブラ・コーポレーション / ZAMLT",
    tier: "歴史的人物",
  },
  {
    id: "エリザベス・リンドバーグ" as WikiId,
    name: "エリザベス・リンドバーグ",
    nameEn: "Elizabeth Lindberg",
    category: "キャラクター",
    subCategory: "ZAMLT",
    description:
      "ルレンツ・コーポレーションのリーダー。プロトコルXの技術設計とカタリスト・コア建造を主導したZAMLTの技術的支柱。次元エネルギーの制御と増幅に関する最先端の研究を指揮し、ZAMLT本社最深部に建造された次元の塔とカタリスト・コアの実現に決定的な役割を果たした。",
    descriptionEn: "Leader of Lorentz Corporation. The technological pillar of ZAMLT who led the technical design of Protocol X and the construction of the Catalyst Core. Directed cutting-edge research on the control and amplification of dimensional energy, playing a decisive role in realizing the Dimensional Tower and Catalyst Core constructed in the deepest depths of ZAMLT headquarters.",
    era: "E301〜E318",
    affiliation: "ルレンツ・コーポレーション / ZAMLT",
    tier: "歴史的人物",
  },
  {
    id: "レイ・ヴァンデルト" as WikiId,
    name: "レイ・ヴァンデルト",
    nameEn: "Ray Vandelte",
    category: "キャラクター",
    subCategory: "ZAMLT",
    description:
      "ゼブラ・コーポレーションの工作員。アーサー・グリムの指示のもと、ZAMLTとEVILSの秘密会合の真相を追及していたコーポラトクラシー「ストロベリー」のCEOアレンをシェンドバーグ次元に閉じ込めて殺害した冷徹な実行部隊の要員。アレンの死はアルファ・ケインとテクロサスを結ぶ決定的な動機となり、ZAMLTに対する全面対決への道を開いた。",
    descriptionEn: "An operative of Zebra Corporation. Under the orders of Arthur Grimm, he was a cold-blooded operative who trapped and killed CEO Allen of the corporatocracy 'Strawberry,' who was investigating the truth behind the secret meeting between ZAMLT and EVILS, in the Schendberg dimension. Allen's death became the decisive motive connecting Alpha Cain and Techlosus, opening the path to a full confrontation with ZAMLT.",
    era: "E318年頃",
    affiliation: "ゼブラ・コーポレーション / ZAMLT",
    tier: "歴史的人物",
  },
  {
    id: "リンダ" as WikiId,
    name: "リンダ",
    nameEn: "Linda",
    category: "キャラクター",
    subCategory: "ZAMLT",
    description:
      "ルレンツ・コーポレーションの研究員。シルバープラント攻略戦において、プロトコルXのエネルギーコアの暴走を安定化させるため自らを犠牲にした悲劇の英雄。彼女の自己犠牲はアルファ・ケインにZAMLT打倒への決意を固めさせ、シャドウ・リベリオンの士気を大きく高めた。ルレンツ・コーポレーション内部でも反ZAMLT感情の広がる転換点となった。",
    descriptionEn: "A researcher at the Lorenz Corporation. During the Silver Plant offensive operation, she became a tragic hero by sacrificing herself to stabilize the runaway energy core of Protocol X. Her self-sacrifice solidified Alpha Kane's determination to defeat ZAMLT and greatly boosted the morale of the Shadow Rebellion. It also marked a turning point within the Lorenz Corporation, spreading anti-ZAMLT sentiments throughout the organization.",
    era: "E318年",
    affiliation: "ルレンツ・コーポレーション / ZAMLT",
    tier: "歴史的人物",
  },

  /* テクロサス系譜 */
  {
    id: "クロノ・ヴァーレント" as WikiId,
    name: "クロノ・ヴァーレント",
    nameEn: "Chrono Valeint",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "テクロサスの指導者の一人。シルバープラント攻略戦でアルファ・ケインと共に戦い、ZAMLT打倒の軍事的支柱として重要な役割を果たした。テクロサス系譜（E15ファランクス〜E295三頭政治〜E470東方支隊〜現在のボグダス・ジャベリン）の中で中核的な役割を担った軍人であり、その軍事的伝統は現在のセバスチャン・ヴァレリウス率いるボグダス・ジャベリンに受け継がれている。",
    descriptionEn: "One of the leaders of Tectlos. He fought alongside Alpha Kane during the Silver Plant offensive operation, playing a crucial role as the military pillar in the fight against ZAMLT. A military figure who played a central role in the Tectlos lineage (E15 Phalanx to E295 Triumvirate to E470 Eastern Detachment to the current Bogdus Javelin), his military tradition is now carried on by the Bogdus Javelin led by Sebastian Valerius.",
    era: "E318年頃",
    affiliation: "テクロサス",
    tier: "歴史的人物",
  },

  /* 宇宙勢力（歴史） */
  {
    id: "オメガ＝ユリシス" as WikiId,
    name: "オメガ＝ユリシス",
    nameEn: "Omega=Ulysses",
    category: "キャラクター",
    subCategory: "宇宙勢力",
    description:
      "EVILS（超越的次元間生命体群）のリーダー。虚無の塔でZAMLT5社のトップと秘密会合を持ち、次元の塔を通じた取引を行った。次元の塔での最終決戦でアルファ・ケインと激突し、伴共役（Ban-Kyōyaku）能力によって次元の繊維に封印された。EVILSは通常の物理法則を超越した存在であり、オメガ＝ユリシスの封印はEDU宇宙論における次元干渉の限界と可能性を示す出来事として記録されている。",
    descriptionEn: "The leader of EVILS (Transdimensional Lifeforms). He held a secret meeting with the head of ZAMLT 5 at the Tower of Nothingness and conducted transactions through the Dimensional Towers. In the final decisive battle at the Dimensional Towers, he clashed with Alpha Kane and was sealed within the dimensional fibers by his Ban-Kyōyaku (Conjugate Pair) ability. EVILS exist beyond conventional physical laws, and the sealing of Omega-Ulysses is recorded as an event that demonstrates the limits and possibilities of dimensional interference in EDU cosmology.",
    era: "E318年頃",
    affiliation: "EVILS",
    tier: "神格・歴史的人物（次元間存在）",
  },

  /* 追加: 共同体指導者 */
  {
    id: "ファランクス（初代皇帝）" as WikiId,
    name: "ファランクス（初代皇帝）",
    nameEn: "Phalanx",
    category: "キャラクター",
    subCategory: "宇宙勢力",
    description:
      "バーズ帝国の初代皇帝。E15年に軍閥ファランクスを率いてE16連星系の初期植民地間紛争を武力によって終結させ、連星系初の包括的統一政権バーズ帝国を樹立した。ファランクスは帝国という名称ながらも、初期の入植者自治の伝統を尊重し、各省庁に相当する地方総督府制度を導入した。E61年の死後、後継者争いによって帝国は分裂したが、その軍事伝統はテクロサス系譜として受け継がれ、現在のボグダス・ジャベリンに至っている。",
    descriptionEn: "The first Emperor of the Bartz Empire. In E15, he led the military faction Phalanx to forcefully end the initial colonial disputes among the E16 star system's colonies, establishing the Bartz Empire—the first comprehensive unified government in the star system. Though called an empire, Phalanx respected the tradition of early settler autonomy and introduced a system of regional governorates equivalent to various ministries. After his death in E61, the empire split due to succession disputes, but its military tradition was carried on through the Tectlos lineage, continuing to the present Bogdus Javelin.",
    era: "E15〜E61",
    affiliation: "バーズ帝国",
    tier: "歴史的人物",
  },
  {
    id: "セルヴァ・ドーン" as WikiId,
    name: "セルヴァ・ドーン",
    nameEn: "Selva Dawn",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "SUDOMの初代医療総裁。E480年代に医療研究特別植民地だったSUDOMを国家へと昇格させ、遺伝子医療と再生医療の分野でE16文明圏の最先端を走る医療国家の基盤を築いた。スライム危機後のリーチ・ドレイン対策医療において中心的役割を果たし、V7加盟後は同盟の医療支援と疫学調査を統括した。",
    descriptionEn: "The first Medical Director of SUDOM. In the E480s, she elevated the special medical research colony of SUDOM to nation status, establishing the foundation for a medical state at the forefront of the E16 civilization in the fields of genetic and regenerative medicine. She played a central role in post-Slime Crisis Leech Drain countermeasures, and after joining V7, she coordinated the alliance's medical support and epidemiological investigations.",
    era: "E480〜",
    affiliation: "SUDOM",
    tier: "Tier 2",
  },
  {
    id: "ハシーム・ファティマ" as WikiId,
    name: "ハシーム・ファティマ",
    nameEn: "Hashim Fatima",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ファティマ連邦の初代連邦議長。E400年代に分散する複数の自治州を緩やかな連合に統合し、宗教的・哲学的自由を重んじる連邦国家の基盤を築いた。ファティマ連邦の名称は彼の家族名に由来する。最小限の統治構造を採る分散型モデルを確立し、ネオクラン同盟の理念と共鳴する外交路線を推進した。",
    descriptionEn: "The first Federal Chairman of the Fatima Federation. In the E400s, he integrated multiple scattered autonomous states into a loose federation, establishing the foundation for a federal state that valued religious and philosophical freedom. The name of the Fatima Federation derives from his family name. He established a decentralized model with minimal governance structures and pursued a diplomatic route that resonated with the ideals of the Neo-Clan Alliance.",
    era: "E400〜",
    affiliation: "ファティマ連邦",
    tier: "Tier 2",
  },
  {
    id: "トリスタン・スターク" as WikiId,
    name: "トリスタン・スターク",
    nameEn: "Tristan Stark",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "スターク三国軍事理事長。E480年代に三国の防衛同盟を近代化し、他勢力への依存を避ける自律的安全保障体制を強化した。V7やトリニティ・アライアンスのいずれにも属さない独自路線を堅持し、クレセント地方の第三勢力として中立地帯の防衛を担う。質量ともに高く評価されるスターク三国軍事力の近代化の立役者。",
    descriptionEn: "The Military Director of the Stark Triumvirate. In the E480s, he modernized the tripartite defense alliance and strengthened an independent security system to avoid reliance on other powers. He maintains an independent course, belonging to neither V7 nor the Trinity Alliance, serving as the third power in the Crescent Region and defending neutral territories. He is the key figure behind the modernization of the Stark Triumvirate's military, highly regarded for both its quality and quantity.",
    era: "E480〜",
    affiliation: "スターク三国",
    tier: "Tier 2",
  },
  {
    id: "オーギュスト・ゴールド" as WikiId,
    name: "オーギュスト・ゴールド",
    nameEn: "August Gold",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ゴールデン・ヴェノムの創設者。シルバー・ヴェノムの内部抗争から独立し、アルファ・ヴェノムの急進的な武力路線に反対してnトークン経済システムへの浸透と金融操作による支配を志向する分派を率いた。表向きは合法的な企業活動を通じて資金を蓄積し、A-Registryシステムへの潜入工作を指揮していると疑われる。その手法は皮肉にもZAMLTの戦略を模倣するものであり、経済的支配による社会変革を最終目標としている。",
    descriptionEn: "The founder of Golden Venom. Breaking away from the internal strife of Silver Venom, he led a faction that opposed Alpha Venom's radical military approach, instead seeking to infiltrate and dominate through the n-token economic system and financial manipulation. He is suspected of accumulating funds through ostensibly legitimate corporate activities and directing infiltration operations into the A-Registry system. Ironically, his methods mimic ZAMLT's strategies, with economic domination leading to social change as his ultimate goal.",
    era: "E500〜",
    affiliation: "ゴールデン・ヴェノム",
    tier: "Tier 2",
  },
  {
    id: "ルシア・ネオ" as WikiId,
    name: "ルシア・ネオ",
    nameEn: "Lucia Neo",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "ネオクラン同盟の初代代表。ZAMLT崩壊後の民主化運動の指導者複数名と共同で分散統治モデルの基盤を築いた。地方自治権の強化と市民参加型政治の復興を掲げ、テクノ文化ルネサンス期の「技術の民主化」という精神を政治制度に具体化した。UECO統合後は銀河系コンソーシアムの中核構成体として機能するネオクラン同盟の理念を代表する外交官として活動した。",
    descriptionEn: "The first representative of the Neo-Clan Alliance. He collaborated with several leaders of the democratization movement following ZAMLT's collapse to establish the foundation of a decentralized governance model. Advocating for strengthened local autonomy and the revival of citizen-participatory politics, he embodied the spirit of 'democratization of technology' from the Techno-Cultural Renaissance into political institutions. After UECO integration, he served as a diplomat representing the Neo-Clan Alliance's ideals as a core component of the Galactic Consortium.",
    era: "E330〜",
    affiliation: "ネオクラン同盟",
    tier: "歴史的人物",
  },
  {
    id: "ヘクトル・ヴァン" as WikiId,
    name: "ヘクトル・ヴァン",
    nameEn: "Hector Van",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "UECO（星間経済協同組合）の初代議長。テクノ文化ルネサンス期の指導者の一人として、ZAMLT崩壊後の経済的混乱を収束させ、nトークン経済システムの再構築と公正な資源配分を実現した。ヒーローエージェンシーとの統合という独自の組織体制を構築し、経済活動と安全保障の有機的連携を実現した。E495〜E500年の銀河系コンソーシアム設立への移行期を主導した。",
    descriptionEn: "The first Chairman of UECO (Interstellar Economic Cooperative). As one of the leaders of the Techno-Cultural Renaissance period, he stabilized the economic chaos following ZAMLT's collapse, reconstructing the n-token economic system and achieving fair resource allocation. He built a unique organizational structure through integration with Hero Agencies, realizing organic coordination between economic activities and security. He led the transition period from E495 to E500 during the establishment of the Galactic Consortium.",
    era: "E400後半〜E500",
    affiliation: "UECO",
    tier: "歴史的人物",
  },
] as const satisfies readonly WikiEntry[]
